// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.5
// source: api/proto/cache.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { StateResponse } from "./quantum";

export const protobufPackage = "qubit_engine";

export interface CacheRequest {
  /** SHA-256 of circuit definition */
  circuitHash: string;
  numQubits: number;
  numOperations: number;
  /** The computed result */
  result:
    | StateResponse
    | undefined;
  /** Time to live (0 = default) */
  ttlSeconds: number;
}

export interface CacheResponse {
  success: boolean;
  message: string;
  cacheKey: string;
}

export interface CacheLookup {
  circuitHash: string;
}

export interface CacheHit {
  found: boolean;
  result:
    | StateResponse
    | undefined;
  /** Unix timestamp */
  cachedAt: number;
  expiresAt: number;
  /** How many times this was retrieved */
  hitCount: number;
}

export interface CacheEmpty {
}

export interface CacheStats {
  totalEntries: number;
  totalHits: number;
  totalMisses: number;
  /** 0.0 to 1.0 */
  hitRate: number;
  memoryUsedBytes: number;
  /** Seconds */
  oldestEntryAge: number;
}

function createBaseCacheRequest(): CacheRequest {
  return { circuitHash: "", numQubits: 0, numOperations: 0, result: undefined, ttlSeconds: 0 };
}

export const CacheRequest: MessageFns<CacheRequest> = {
  encode(message: CacheRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuitHash !== "") {
      writer.uint32(10).string(message.circuitHash);
    }
    if (message.numQubits !== 0) {
      writer.uint32(16).int32(message.numQubits);
    }
    if (message.numOperations !== 0) {
      writer.uint32(24).int32(message.numOperations);
    }
    if (message.result !== undefined) {
      StateResponse.encode(message.result, writer.uint32(34).fork()).join();
    }
    if (message.ttlSeconds !== 0) {
      writer.uint32(40).int32(message.ttlSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuitHash = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.numQubits = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.numOperations = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.result = StateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.ttlSeconds = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CacheRequest {
    return {
      circuitHash: isSet(object.circuitHash)
        ? globalThis.String(object.circuitHash)
        : isSet(object.circuit_hash)
        ? globalThis.String(object.circuit_hash)
        : "",
      numQubits: isSet(object.numQubits)
        ? globalThis.Number(object.numQubits)
        : isSet(object.num_qubits)
        ? globalThis.Number(object.num_qubits)
        : 0,
      numOperations: isSet(object.numOperations)
        ? globalThis.Number(object.numOperations)
        : isSet(object.num_operations)
        ? globalThis.Number(object.num_operations)
        : 0,
      result: isSet(object.result) ? StateResponse.fromJSON(object.result) : undefined,
      ttlSeconds: isSet(object.ttlSeconds)
        ? globalThis.Number(object.ttlSeconds)
        : isSet(object.ttl_seconds)
        ? globalThis.Number(object.ttl_seconds)
        : 0,
    };
  },

  toJSON(message: CacheRequest): unknown {
    const obj: any = {};
    if (message.circuitHash !== "") {
      obj.circuitHash = message.circuitHash;
    }
    if (message.numQubits !== 0) {
      obj.numQubits = Math.round(message.numQubits);
    }
    if (message.numOperations !== 0) {
      obj.numOperations = Math.round(message.numOperations);
    }
    if (message.result !== undefined) {
      obj.result = StateResponse.toJSON(message.result);
    }
    if (message.ttlSeconds !== 0) {
      obj.ttlSeconds = Math.round(message.ttlSeconds);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheRequest>, I>>(base?: I): CacheRequest {
    return CacheRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheRequest>, I>>(object: I): CacheRequest {
    const message = createBaseCacheRequest();
    message.circuitHash = object.circuitHash ?? "";
    message.numQubits = object.numQubits ?? 0;
    message.numOperations = object.numOperations ?? 0;
    message.result = (object.result !== undefined && object.result !== null)
      ? StateResponse.fromPartial(object.result)
      : undefined;
    message.ttlSeconds = object.ttlSeconds ?? 0;
    return message;
  },
};

function createBaseCacheResponse(): CacheResponse {
  return { success: false, message: "", cacheKey: "" };
}

export const CacheResponse: MessageFns<CacheResponse> = {
  encode(message: CacheResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.cacheKey !== "") {
      writer.uint32(26).string(message.cacheKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cacheKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CacheResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      cacheKey: isSet(object.cacheKey)
        ? globalThis.String(object.cacheKey)
        : isSet(object.cache_key)
        ? globalThis.String(object.cache_key)
        : "",
    };
  },

  toJSON(message: CacheResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.cacheKey !== "") {
      obj.cacheKey = message.cacheKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheResponse>, I>>(base?: I): CacheResponse {
    return CacheResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheResponse>, I>>(object: I): CacheResponse {
    const message = createBaseCacheResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    message.cacheKey = object.cacheKey ?? "";
    return message;
  },
};

function createBaseCacheLookup(): CacheLookup {
  return { circuitHash: "" };
}

export const CacheLookup: MessageFns<CacheLookup> = {
  encode(message: CacheLookup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuitHash !== "") {
      writer.uint32(10).string(message.circuitHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheLookup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheLookup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuitHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CacheLookup {
    return {
      circuitHash: isSet(object.circuitHash)
        ? globalThis.String(object.circuitHash)
        : isSet(object.circuit_hash)
        ? globalThis.String(object.circuit_hash)
        : "",
    };
  },

  toJSON(message: CacheLookup): unknown {
    const obj: any = {};
    if (message.circuitHash !== "") {
      obj.circuitHash = message.circuitHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheLookup>, I>>(base?: I): CacheLookup {
    return CacheLookup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheLookup>, I>>(object: I): CacheLookup {
    const message = createBaseCacheLookup();
    message.circuitHash = object.circuitHash ?? "";
    return message;
  },
};

function createBaseCacheHit(): CacheHit {
  return { found: false, result: undefined, cachedAt: 0, expiresAt: 0, hitCount: 0 };
}

export const CacheHit: MessageFns<CacheHit> = {
  encode(message: CacheHit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.found !== false) {
      writer.uint32(8).bool(message.found);
    }
    if (message.result !== undefined) {
      StateResponse.encode(message.result, writer.uint32(18).fork()).join();
    }
    if (message.cachedAt !== 0) {
      writer.uint32(24).int64(message.cachedAt);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(32).int64(message.expiresAt);
    }
    if (message.hitCount !== 0) {
      writer.uint32(40).int32(message.hitCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheHit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheHit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.found = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.result = StateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.cachedAt = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.hitCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CacheHit {
    return {
      found: isSet(object.found) ? globalThis.Boolean(object.found) : false,
      result: isSet(object.result) ? StateResponse.fromJSON(object.result) : undefined,
      cachedAt: isSet(object.cachedAt)
        ? globalThis.Number(object.cachedAt)
        : isSet(object.cached_at)
        ? globalThis.Number(object.cached_at)
        : 0,
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      hitCount: isSet(object.hitCount)
        ? globalThis.Number(object.hitCount)
        : isSet(object.hit_count)
        ? globalThis.Number(object.hit_count)
        : 0,
    };
  },

  toJSON(message: CacheHit): unknown {
    const obj: any = {};
    if (message.found !== false) {
      obj.found = message.found;
    }
    if (message.result !== undefined) {
      obj.result = StateResponse.toJSON(message.result);
    }
    if (message.cachedAt !== 0) {
      obj.cachedAt = Math.round(message.cachedAt);
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.hitCount !== 0) {
      obj.hitCount = Math.round(message.hitCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheHit>, I>>(base?: I): CacheHit {
    return CacheHit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheHit>, I>>(object: I): CacheHit {
    const message = createBaseCacheHit();
    message.found = object.found ?? false;
    message.result = (object.result !== undefined && object.result !== null)
      ? StateResponse.fromPartial(object.result)
      : undefined;
    message.cachedAt = object.cachedAt ?? 0;
    message.expiresAt = object.expiresAt ?? 0;
    message.hitCount = object.hitCount ?? 0;
    return message;
  },
};

function createBaseCacheEmpty(): CacheEmpty {
  return {};
}

export const CacheEmpty: MessageFns<CacheEmpty> = {
  encode(_: CacheEmpty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheEmpty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CacheEmpty {
    return {};
  },

  toJSON(_: CacheEmpty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheEmpty>, I>>(base?: I): CacheEmpty {
    return CacheEmpty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheEmpty>, I>>(_: I): CacheEmpty {
    const message = createBaseCacheEmpty();
    return message;
  },
};

function createBaseCacheStats(): CacheStats {
  return { totalEntries: 0, totalHits: 0, totalMisses: 0, hitRate: 0, memoryUsedBytes: 0, oldestEntryAge: 0 };
}

export const CacheStats: MessageFns<CacheStats> = {
  encode(message: CacheStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalEntries !== 0) {
      writer.uint32(8).int64(message.totalEntries);
    }
    if (message.totalHits !== 0) {
      writer.uint32(16).int64(message.totalHits);
    }
    if (message.totalMisses !== 0) {
      writer.uint32(24).int64(message.totalMisses);
    }
    if (message.hitRate !== 0) {
      writer.uint32(33).double(message.hitRate);
    }
    if (message.memoryUsedBytes !== 0) {
      writer.uint32(40).int64(message.memoryUsedBytes);
    }
    if (message.oldestEntryAge !== 0) {
      writer.uint32(48).int64(message.oldestEntryAge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CacheStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCacheStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalEntries = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalHits = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalMisses = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.hitRate = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.memoryUsedBytes = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.oldestEntryAge = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CacheStats {
    return {
      totalEntries: isSet(object.totalEntries)
        ? globalThis.Number(object.totalEntries)
        : isSet(object.total_entries)
        ? globalThis.Number(object.total_entries)
        : 0,
      totalHits: isSet(object.totalHits)
        ? globalThis.Number(object.totalHits)
        : isSet(object.total_hits)
        ? globalThis.Number(object.total_hits)
        : 0,
      totalMisses: isSet(object.totalMisses)
        ? globalThis.Number(object.totalMisses)
        : isSet(object.total_misses)
        ? globalThis.Number(object.total_misses)
        : 0,
      hitRate: isSet(object.hitRate)
        ? globalThis.Number(object.hitRate)
        : isSet(object.hit_rate)
        ? globalThis.Number(object.hit_rate)
        : 0,
      memoryUsedBytes: isSet(object.memoryUsedBytes)
        ? globalThis.Number(object.memoryUsedBytes)
        : isSet(object.memory_used_bytes)
        ? globalThis.Number(object.memory_used_bytes)
        : 0,
      oldestEntryAge: isSet(object.oldestEntryAge)
        ? globalThis.Number(object.oldestEntryAge)
        : isSet(object.oldest_entry_age)
        ? globalThis.Number(object.oldest_entry_age)
        : 0,
    };
  },

  toJSON(message: CacheStats): unknown {
    const obj: any = {};
    if (message.totalEntries !== 0) {
      obj.totalEntries = Math.round(message.totalEntries);
    }
    if (message.totalHits !== 0) {
      obj.totalHits = Math.round(message.totalHits);
    }
    if (message.totalMisses !== 0) {
      obj.totalMisses = Math.round(message.totalMisses);
    }
    if (message.hitRate !== 0) {
      obj.hitRate = message.hitRate;
    }
    if (message.memoryUsedBytes !== 0) {
      obj.memoryUsedBytes = Math.round(message.memoryUsedBytes);
    }
    if (message.oldestEntryAge !== 0) {
      obj.oldestEntryAge = Math.round(message.oldestEntryAge);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CacheStats>, I>>(base?: I): CacheStats {
    return CacheStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CacheStats>, I>>(object: I): CacheStats {
    const message = createBaseCacheStats();
    message.totalEntries = object.totalEntries ?? 0;
    message.totalHits = object.totalHits ?? 0;
    message.totalMisses = object.totalMisses ?? 0;
    message.hitRate = object.hitRate ?? 0;
    message.memoryUsedBytes = object.memoryUsedBytes ?? 0;
    message.oldestEntryAge = object.oldestEntryAge ?? 0;
    return message;
  },
};

export type ResultCacheService = typeof ResultCacheService;
export const ResultCacheService = {
  /** Store a circuit result in cache */
  cacheResult: {
    path: "/qubit_engine.ResultCache/CacheResult" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CacheRequest): Buffer => Buffer.from(CacheRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CacheRequest => CacheRequest.decode(value),
    responseSerialize: (value: CacheResponse): Buffer => Buffer.from(CacheResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CacheResponse => CacheResponse.decode(value),
  },
  /** Retrieve a cached result */
  getCachedResult: {
    path: "/qubit_engine.ResultCache/GetCachedResult" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CacheLookup): Buffer => Buffer.from(CacheLookup.encode(value).finish()),
    requestDeserialize: (value: Buffer): CacheLookup => CacheLookup.decode(value),
    responseSerialize: (value: CacheHit): Buffer => Buffer.from(CacheHit.encode(value).finish()),
    responseDeserialize: (value: Buffer): CacheHit => CacheHit.decode(value),
  },
  /** Invalidate a cached result */
  invalidateCache: {
    path: "/qubit_engine.ResultCache/InvalidateCache" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CacheLookup): Buffer => Buffer.from(CacheLookup.encode(value).finish()),
    requestDeserialize: (value: Buffer): CacheLookup => CacheLookup.decode(value),
    responseSerialize: (value: CacheResponse): Buffer => Buffer.from(CacheResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CacheResponse => CacheResponse.decode(value),
  },
  /** Get cache statistics */
  getCacheStats: {
    path: "/qubit_engine.ResultCache/GetCacheStats" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CacheEmpty): Buffer => Buffer.from(CacheEmpty.encode(value).finish()),
    requestDeserialize: (value: Buffer): CacheEmpty => CacheEmpty.decode(value),
    responseSerialize: (value: CacheStats): Buffer => Buffer.from(CacheStats.encode(value).finish()),
    responseDeserialize: (value: Buffer): CacheStats => CacheStats.decode(value),
  },
} as const;

export interface ResultCacheServer extends UntypedServiceImplementation {
  /** Store a circuit result in cache */
  cacheResult: handleUnaryCall<CacheRequest, CacheResponse>;
  /** Retrieve a cached result */
  getCachedResult: handleUnaryCall<CacheLookup, CacheHit>;
  /** Invalidate a cached result */
  invalidateCache: handleUnaryCall<CacheLookup, CacheResponse>;
  /** Get cache statistics */
  getCacheStats: handleUnaryCall<CacheEmpty, CacheStats>;
}

export interface ResultCacheClient extends Client {
  /** Store a circuit result in cache */
  cacheResult(
    request: CacheRequest,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  cacheResult(
    request: CacheRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  cacheResult(
    request: CacheRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  /** Retrieve a cached result */
  getCachedResult(
    request: CacheLookup,
    callback: (error: ServiceError | null, response: CacheHit) => void,
  ): ClientUnaryCall;
  getCachedResult(
    request: CacheLookup,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CacheHit) => void,
  ): ClientUnaryCall;
  getCachedResult(
    request: CacheLookup,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CacheHit) => void,
  ): ClientUnaryCall;
  /** Invalidate a cached result */
  invalidateCache(
    request: CacheLookup,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  invalidateCache(
    request: CacheLookup,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  invalidateCache(
    request: CacheLookup,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CacheResponse) => void,
  ): ClientUnaryCall;
  /** Get cache statistics */
  getCacheStats(
    request: CacheEmpty,
    callback: (error: ServiceError | null, response: CacheStats) => void,
  ): ClientUnaryCall;
  getCacheStats(
    request: CacheEmpty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CacheStats) => void,
  ): ClientUnaryCall;
  getCacheStats(
    request: CacheEmpty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CacheStats) => void,
  ): ClientUnaryCall;
}

export const ResultCacheClient = makeGenericClientConstructor(
  ResultCacheService,
  "qubit_engine.ResultCache",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ResultCacheClient;
  service: typeof ResultCacheService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
