// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: api/proto/quantum.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleBidiStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "qubit_engine";

export interface CircuitRequest {
  numQubits: number;
  operations: GateOperation[];
  /** Probability of a depolarizing error occurring per step (0.0 - 1.0) */
  noiseProbability: number;
  executionBackend: CircuitRequest_ExecutionBackend;
  measurementStrategy: CircuitRequest_MeasurementStrategy;
  useShm: boolean;
}

export enum CircuitRequest_ExecutionBackend {
  SIMULATOR = 0,
  MOCK_HARDWARE = 1,
  /** REAL_IBM_Q - Future use */
  REAL_IBM_Q = 2,
  UNRECOGNIZED = -1,
}

export function circuitRequest_ExecutionBackendFromJSON(object: any): CircuitRequest_ExecutionBackend {
  switch (object) {
    case 0:
    case "SIMULATOR":
      return CircuitRequest_ExecutionBackend.SIMULATOR;
    case 1:
    case "MOCK_HARDWARE":
      return CircuitRequest_ExecutionBackend.MOCK_HARDWARE;
    case 2:
    case "REAL_IBM_Q":
      return CircuitRequest_ExecutionBackend.REAL_IBM_Q;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CircuitRequest_ExecutionBackend.UNRECOGNIZED;
  }
}

export function circuitRequest_ExecutionBackendToJSON(object: CircuitRequest_ExecutionBackend): string {
  switch (object) {
    case CircuitRequest_ExecutionBackend.SIMULATOR:
      return "SIMULATOR";
    case CircuitRequest_ExecutionBackend.MOCK_HARDWARE:
      return "MOCK_HARDWARE";
    case CircuitRequest_ExecutionBackend.REAL_IBM_Q:
      return "REAL_IBM_Q";
    case CircuitRequest_ExecutionBackend.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum CircuitRequest_MeasurementStrategy {
  FULL_STATE = 0,
  SPARSE_STATE = 1,
  EXPECTATION_VALUES = 2,
  UNRECOGNIZED = -1,
}

export function circuitRequest_MeasurementStrategyFromJSON(object: any): CircuitRequest_MeasurementStrategy {
  switch (object) {
    case 0:
    case "FULL_STATE":
      return CircuitRequest_MeasurementStrategy.FULL_STATE;
    case 1:
    case "SPARSE_STATE":
      return CircuitRequest_MeasurementStrategy.SPARSE_STATE;
    case 2:
    case "EXPECTATION_VALUES":
      return CircuitRequest_MeasurementStrategy.EXPECTATION_VALUES;
    case -1:
    case "UNRECOGNIZED":
    default:
      return CircuitRequest_MeasurementStrategy.UNRECOGNIZED;
  }
}

export function circuitRequest_MeasurementStrategyToJSON(object: CircuitRequest_MeasurementStrategy): string {
  switch (object) {
    case CircuitRequest_MeasurementStrategy.FULL_STATE:
      return "FULL_STATE";
    case CircuitRequest_MeasurementStrategy.SPARSE_STATE:
      return "SPARSE_STATE";
    case CircuitRequest_MeasurementStrategy.EXPECTATION_VALUES:
      return "EXPECTATION_VALUES";
    case CircuitRequest_MeasurementStrategy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GateOperation {
  type: GateOperation_GateType;
  targetQubit: number;
  controlQubit: number;
  /** Register to store the classical measurement result */
  classicalRegister: number;
  /** Rotation angle in radians (for RX, RY, RZ gates) */
  angle: number;
  /** For Toffoli (second control qubit) */
  secondControlQubit: number;
  /** For SWAP and two-target gates (second target qubit) */
  secondTargetQubit: number;
  /** For DEPOLARIZING_NOISE (error probability 0.0 - 1.0) */
  noiseProbability: number;
}

export enum GateOperation_GateType {
  HADAMARD = 0,
  PAULI_X = 1,
  CNOT = 2,
  MEASURE = 3,
  TOFFOLI = 4,
  /** PHASE_S - S Gate (Z90) */
  PHASE_S = 5,
  /** PHASE_T - T Gate (Z45) */
  PHASE_T = 6,
  ROTATION_Y = 7,
  ROTATION_Z = 8,
  PAULI_Y = 9,
  PAULI_Z = 10,
  ROTATION_X = 11,
  SWAP = 12,
  CZ = 13,
  DEPOLARIZING_NOISE = 14,
  UNRECOGNIZED = -1,
}

export function gateOperation_GateTypeFromJSON(object: any): GateOperation_GateType {
  switch (object) {
    case 0:
    case "HADAMARD":
      return GateOperation_GateType.HADAMARD;
    case 1:
    case "PAULI_X":
      return GateOperation_GateType.PAULI_X;
    case 2:
    case "CNOT":
      return GateOperation_GateType.CNOT;
    case 3:
    case "MEASURE":
      return GateOperation_GateType.MEASURE;
    case 4:
    case "TOFFOLI":
      return GateOperation_GateType.TOFFOLI;
    case 5:
    case "PHASE_S":
      return GateOperation_GateType.PHASE_S;
    case 6:
    case "PHASE_T":
      return GateOperation_GateType.PHASE_T;
    case 7:
    case "ROTATION_Y":
      return GateOperation_GateType.ROTATION_Y;
    case 8:
    case "ROTATION_Z":
      return GateOperation_GateType.ROTATION_Z;
    case 9:
    case "PAULI_Y":
      return GateOperation_GateType.PAULI_Y;
    case 10:
    case "PAULI_Z":
      return GateOperation_GateType.PAULI_Z;
    case 11:
    case "ROTATION_X":
      return GateOperation_GateType.ROTATION_X;
    case 12:
    case "SWAP":
      return GateOperation_GateType.SWAP;
    case 13:
    case "CZ":
      return GateOperation_GateType.CZ;
    case 14:
    case "DEPOLARIZING_NOISE":
      return GateOperation_GateType.DEPOLARIZING_NOISE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GateOperation_GateType.UNRECOGNIZED;
  }
}

export function gateOperation_GateTypeToJSON(object: GateOperation_GateType): string {
  switch (object) {
    case GateOperation_GateType.HADAMARD:
      return "HADAMARD";
    case GateOperation_GateType.PAULI_X:
      return "PAULI_X";
    case GateOperation_GateType.CNOT:
      return "CNOT";
    case GateOperation_GateType.MEASURE:
      return "MEASURE";
    case GateOperation_GateType.TOFFOLI:
      return "TOFFOLI";
    case GateOperation_GateType.PHASE_S:
      return "PHASE_S";
    case GateOperation_GateType.PHASE_T:
      return "PHASE_T";
    case GateOperation_GateType.ROTATION_Y:
      return "ROTATION_Y";
    case GateOperation_GateType.ROTATION_Z:
      return "ROTATION_Z";
    case GateOperation_GateType.PAULI_Y:
      return "PAULI_Y";
    case GateOperation_GateType.PAULI_Z:
      return "PAULI_Z";
    case GateOperation_GateType.ROTATION_X:
      return "ROTATION_X";
    case GateOperation_GateType.SWAP:
      return "SWAP";
    case GateOperation_GateType.CZ:
      return "CZ";
    case GateOperation_GateType.DEPOLARIZING_NOISE:
      return "DEPOLARIZING_NOISE";
    case GateOperation_GateType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface GateStreamInit {
  numQubits: number;
  /** Optional: if true, server may return shm_descriptor instead of state_vector. */
  useShm: boolean;
}

export interface GateStreamRequest {
  init?: GateStreamInit | undefined;
  op?: GateOperation | undefined;
}

export interface StateResponse {
  /** The full state vector of size 2^num_qubits */
  stateVector: StateResponse_ComplexNumber[];
  /** Return measured classical bits (e.g., Qubit 0 -> 1) */
  classicalResults: { [key: number]: boolean };
  /** Identity of the server (Hostname/Pod ID) that processed this step */
  serverId: string;
  /** Sparse representations if Strategy != FULL_STATE */
  sparseStates: Measurement[];
  expectationValues: number[];
  /** Shared memory descriptor if Zero-Copy IPC is utilized */
  shmDescriptor: string;
}

export interface StateResponse_ComplexNumber {
  /** Note: Using 'double' is standard for quantum state vectors. */
  real: number;
  imag: number;
}

export interface StateResponse_ClassicalResultsEntry {
  key: number;
  value: boolean;
}

export interface Measurement {
  qubitIndex: number;
  result: boolean;
  /** Probability of the measured result */
  probability: number;
}

export interface PauliTerm {
  pauliString: string;
  coefficient: number;
}

export interface VQERequest {
  /** @deprecated */
  molecule: VQERequest_Molecule;
  maxIterations: number;
  /** For Gradient Descent */
  learningRate: number;
  optimizerType: VQERequest_OptimizerType;
  observables: PauliTerm[];
}

export enum VQERequest_Molecule {
  /** H2 - Hydrogen molecule */
  H2 = 0,
  /** LiH - Lithium Hydride */
  LiH = 1,
  UNRECOGNIZED = -1,
}

export function vQERequest_MoleculeFromJSON(object: any): VQERequest_Molecule {
  switch (object) {
    case 0:
    case "H2":
      return VQERequest_Molecule.H2;
    case 1:
    case "LiH":
      return VQERequest_Molecule.LiH;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VQERequest_Molecule.UNRECOGNIZED;
  }
}

export function vQERequest_MoleculeToJSON(object: VQERequest_Molecule): string {
  switch (object) {
    case VQERequest_Molecule.H2:
      return "H2";
    case VQERequest_Molecule.LiH:
      return "LiH";
    case VQERequest_Molecule.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum VQERequest_OptimizerType {
  /** SPSA - Simultaneous Perturbation Stochastic Approximation */
  SPSA = 0,
  /** GRADIENT_DESCENT - Native Differentiable Simulation (Parameter Shift) */
  GRADIENT_DESCENT = 1,
  UNRECOGNIZED = -1,
}

export function vQERequest_OptimizerTypeFromJSON(object: any): VQERequest_OptimizerType {
  switch (object) {
    case 0:
    case "SPSA":
      return VQERequest_OptimizerType.SPSA;
    case 1:
    case "GRADIENT_DESCENT":
      return VQERequest_OptimizerType.GRADIENT_DESCENT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VQERequest_OptimizerType.UNRECOGNIZED;
  }
}

export function vQERequest_OptimizerTypeToJSON(object: VQERequest_OptimizerType): string {
  switch (object) {
    case VQERequest_OptimizerType.SPSA:
      return "SPSA";
    case VQERequest_OptimizerType.GRADIENT_DESCENT:
      return "GRADIENT_DESCENT";
    case VQERequest_OptimizerType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface VQEResponse {
  iteration: number;
  /** Expected energy in Hartrees */
  energy: number;
  /** Current ansatz parameters (angles) */
  parameters: number[];
  converged: boolean;
}

/** Empty for now, could specify backend types later */
export interface HardwareTopologyRequest {
}

export interface QubitNode {
  id: number;
  x: number;
  y: number;
}

export interface CouplerEdge {
  node1: number;
  node2: number;
}

export interface HardwareTopologyResponse {
  nodes: QubitNode[];
  edges: CouplerEdge[];
}

function createBaseCircuitRequest(): CircuitRequest {
  return {
    numQubits: 0,
    operations: [],
    noiseProbability: 0,
    executionBackend: 0,
    measurementStrategy: 0,
    useShm: false,
  };
}

export const CircuitRequest: MessageFns<CircuitRequest> = {
  encode(message: CircuitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.numQubits !== 0) {
      writer.uint32(8).int32(message.numQubits);
    }
    for (const v of message.operations) {
      GateOperation.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.noiseProbability !== 0) {
      writer.uint32(25).double(message.noiseProbability);
    }
    if (message.executionBackend !== 0) {
      writer.uint32(32).int32(message.executionBackend);
    }
    if (message.measurementStrategy !== 0) {
      writer.uint32(40).int32(message.measurementStrategy);
    }
    if (message.useShm !== false) {
      writer.uint32(48).bool(message.useShm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CircuitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCircuitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.numQubits = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.operations.push(GateOperation.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.noiseProbability = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.executionBackend = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.measurementStrategy = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.useShm = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CircuitRequest {
    return {
      numQubits: isSet(object.numQubits)
        ? globalThis.Number(object.numQubits)
        : isSet(object.num_qubits)
        ? globalThis.Number(object.num_qubits)
        : 0,
      operations: globalThis.Array.isArray(object?.operations)
        ? object.operations.map((e: any) => GateOperation.fromJSON(e))
        : [],
      noiseProbability: isSet(object.noiseProbability)
        ? globalThis.Number(object.noiseProbability)
        : isSet(object.noise_probability)
        ? globalThis.Number(object.noise_probability)
        : 0,
      executionBackend: isSet(object.executionBackend)
        ? circuitRequest_ExecutionBackendFromJSON(object.executionBackend)
        : isSet(object.execution_backend)
        ? circuitRequest_ExecutionBackendFromJSON(object.execution_backend)
        : 0,
      measurementStrategy: isSet(object.measurementStrategy)
        ? circuitRequest_MeasurementStrategyFromJSON(object.measurementStrategy)
        : isSet(object.measurement_strategy)
        ? circuitRequest_MeasurementStrategyFromJSON(object.measurement_strategy)
        : 0,
      useShm: isSet(object.useShm)
        ? globalThis.Boolean(object.useShm)
        : isSet(object.use_shm)
        ? globalThis.Boolean(object.use_shm)
        : false,
    };
  },

  toJSON(message: CircuitRequest): unknown {
    const obj: any = {};
    if (message.numQubits !== 0) {
      obj.numQubits = Math.round(message.numQubits);
    }
    if (message.operations?.length) {
      obj.operations = message.operations.map((e) => GateOperation.toJSON(e));
    }
    if (message.noiseProbability !== 0) {
      obj.noiseProbability = message.noiseProbability;
    }
    if (message.executionBackend !== 0) {
      obj.executionBackend = circuitRequest_ExecutionBackendToJSON(message.executionBackend);
    }
    if (message.measurementStrategy !== 0) {
      obj.measurementStrategy = circuitRequest_MeasurementStrategyToJSON(message.measurementStrategy);
    }
    if (message.useShm !== false) {
      obj.useShm = message.useShm;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CircuitRequest>, I>>(base?: I): CircuitRequest {
    return CircuitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CircuitRequest>, I>>(object: I): CircuitRequest {
    const message = createBaseCircuitRequest();
    message.numQubits = object.numQubits ?? 0;
    message.operations = object.operations?.map((e) => GateOperation.fromPartial(e)) || [];
    message.noiseProbability = object.noiseProbability ?? 0;
    message.executionBackend = object.executionBackend ?? 0;
    message.measurementStrategy = object.measurementStrategy ?? 0;
    message.useShm = object.useShm ?? false;
    return message;
  },
};

function createBaseGateOperation(): GateOperation {
  return {
    type: 0,
    targetQubit: 0,
    controlQubit: 0,
    classicalRegister: 0,
    angle: 0,
    secondControlQubit: 0,
    secondTargetQubit: 0,
    noiseProbability: 0,
  };
}

export const GateOperation: MessageFns<GateOperation> = {
  encode(message: GateOperation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.targetQubit !== 0) {
      writer.uint32(16).uint32(message.targetQubit);
    }
    if (message.controlQubit !== 0) {
      writer.uint32(24).uint32(message.controlQubit);
    }
    if (message.classicalRegister !== 0) {
      writer.uint32(32).uint32(message.classicalRegister);
    }
    if (message.angle !== 0) {
      writer.uint32(41).double(message.angle);
    }
    if (message.secondControlQubit !== 0) {
      writer.uint32(48).uint32(message.secondControlQubit);
    }
    if (message.secondTargetQubit !== 0) {
      writer.uint32(56).uint32(message.secondTargetQubit);
    }
    if (message.noiseProbability !== 0) {
      writer.uint32(65).double(message.noiseProbability);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GateOperation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGateOperation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.targetQubit = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.controlQubit = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.classicalRegister = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.angle = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.secondControlQubit = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.secondTargetQubit = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.noiseProbability = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GateOperation {
    return {
      type: isSet(object.type) ? gateOperation_GateTypeFromJSON(object.type) : 0,
      targetQubit: isSet(object.targetQubit)
        ? globalThis.Number(object.targetQubit)
        : isSet(object.target_qubit)
        ? globalThis.Number(object.target_qubit)
        : 0,
      controlQubit: isSet(object.controlQubit)
        ? globalThis.Number(object.controlQubit)
        : isSet(object.control_qubit)
        ? globalThis.Number(object.control_qubit)
        : 0,
      classicalRegister: isSet(object.classicalRegister)
        ? globalThis.Number(object.classicalRegister)
        : isSet(object.classical_register)
        ? globalThis.Number(object.classical_register)
        : 0,
      angle: isSet(object.angle) ? globalThis.Number(object.angle) : 0,
      secondControlQubit: isSet(object.secondControlQubit)
        ? globalThis.Number(object.secondControlQubit)
        : isSet(object.second_control_qubit)
        ? globalThis.Number(object.second_control_qubit)
        : 0,
      secondTargetQubit: isSet(object.secondTargetQubit)
        ? globalThis.Number(object.secondTargetQubit)
        : isSet(object.second_target_qubit)
        ? globalThis.Number(object.second_target_qubit)
        : 0,
      noiseProbability: isSet(object.noiseProbability)
        ? globalThis.Number(object.noiseProbability)
        : isSet(object.noise_probability)
        ? globalThis.Number(object.noise_probability)
        : 0,
    };
  },

  toJSON(message: GateOperation): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = gateOperation_GateTypeToJSON(message.type);
    }
    if (message.targetQubit !== 0) {
      obj.targetQubit = Math.round(message.targetQubit);
    }
    if (message.controlQubit !== 0) {
      obj.controlQubit = Math.round(message.controlQubit);
    }
    if (message.classicalRegister !== 0) {
      obj.classicalRegister = Math.round(message.classicalRegister);
    }
    if (message.angle !== 0) {
      obj.angle = message.angle;
    }
    if (message.secondControlQubit !== 0) {
      obj.secondControlQubit = Math.round(message.secondControlQubit);
    }
    if (message.secondTargetQubit !== 0) {
      obj.secondTargetQubit = Math.round(message.secondTargetQubit);
    }
    if (message.noiseProbability !== 0) {
      obj.noiseProbability = message.noiseProbability;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GateOperation>, I>>(base?: I): GateOperation {
    return GateOperation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GateOperation>, I>>(object: I): GateOperation {
    const message = createBaseGateOperation();
    message.type = object.type ?? 0;
    message.targetQubit = object.targetQubit ?? 0;
    message.controlQubit = object.controlQubit ?? 0;
    message.classicalRegister = object.classicalRegister ?? 0;
    message.angle = object.angle ?? 0;
    message.secondControlQubit = object.secondControlQubit ?? 0;
    message.secondTargetQubit = object.secondTargetQubit ?? 0;
    message.noiseProbability = object.noiseProbability ?? 0;
    return message;
  },
};

function createBaseGateStreamInit(): GateStreamInit {
  return { numQubits: 0, useShm: false };
}

export const GateStreamInit: MessageFns<GateStreamInit> = {
  encode(message: GateStreamInit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.numQubits !== 0) {
      writer.uint32(8).int32(message.numQubits);
    }
    if (message.useShm !== false) {
      writer.uint32(16).bool(message.useShm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GateStreamInit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGateStreamInit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.numQubits = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.useShm = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GateStreamInit {
    return {
      numQubits: isSet(object.numQubits)
        ? globalThis.Number(object.numQubits)
        : isSet(object.num_qubits)
        ? globalThis.Number(object.num_qubits)
        : 0,
      useShm: isSet(object.useShm)
        ? globalThis.Boolean(object.useShm)
        : isSet(object.use_shm)
        ? globalThis.Boolean(object.use_shm)
        : false,
    };
  },

  toJSON(message: GateStreamInit): unknown {
    const obj: any = {};
    if (message.numQubits !== 0) {
      obj.numQubits = Math.round(message.numQubits);
    }
    if (message.useShm !== false) {
      obj.useShm = message.useShm;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GateStreamInit>, I>>(base?: I): GateStreamInit {
    return GateStreamInit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GateStreamInit>, I>>(object: I): GateStreamInit {
    const message = createBaseGateStreamInit();
    message.numQubits = object.numQubits ?? 0;
    message.useShm = object.useShm ?? false;
    return message;
  },
};

function createBaseGateStreamRequest(): GateStreamRequest {
  return { init: undefined, op: undefined };
}

export const GateStreamRequest: MessageFns<GateStreamRequest> = {
  encode(message: GateStreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.init !== undefined) {
      GateStreamInit.encode(message.init, writer.uint32(10).fork()).join();
    }
    if (message.op !== undefined) {
      GateOperation.encode(message.op, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GateStreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGateStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.init = GateStreamInit.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.op = GateOperation.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GateStreamRequest {
    return {
      init: isSet(object.init) ? GateStreamInit.fromJSON(object.init) : undefined,
      op: isSet(object.op) ? GateOperation.fromJSON(object.op) : undefined,
    };
  },

  toJSON(message: GateStreamRequest): unknown {
    const obj: any = {};
    if (message.init !== undefined) {
      obj.init = GateStreamInit.toJSON(message.init);
    }
    if (message.op !== undefined) {
      obj.op = GateOperation.toJSON(message.op);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GateStreamRequest>, I>>(base?: I): GateStreamRequest {
    return GateStreamRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GateStreamRequest>, I>>(object: I): GateStreamRequest {
    const message = createBaseGateStreamRequest();
    message.init = (object.init !== undefined && object.init !== null)
      ? GateStreamInit.fromPartial(object.init)
      : undefined;
    message.op = (object.op !== undefined && object.op !== null) ? GateOperation.fromPartial(object.op) : undefined;
    return message;
  },
};

function createBaseStateResponse(): StateResponse {
  return {
    stateVector: [],
    classicalResults: {},
    serverId: "",
    sparseStates: [],
    expectationValues: [],
    shmDescriptor: "",
  };
}

export const StateResponse: MessageFns<StateResponse> = {
  encode(message: StateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.stateVector) {
      StateResponse_ComplexNumber.encode(v!, writer.uint32(10).fork()).join();
    }
    globalThis.Object.entries(message.classicalResults).forEach(([key, value]: [string, boolean]) => {
      StateResponse_ClassicalResultsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    if (message.serverId !== "") {
      writer.uint32(26).string(message.serverId);
    }
    for (const v of message.sparseStates) {
      Measurement.encode(v!, writer.uint32(34).fork()).join();
    }
    writer.uint32(42).fork();
    for (const v of message.expectationValues) {
      writer.double(v);
    }
    writer.join();
    if (message.shmDescriptor !== "") {
      writer.uint32(50).string(message.shmDescriptor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stateVector.push(StateResponse_ComplexNumber.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = StateResponse_ClassicalResultsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.classicalResults[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sparseStates.push(Measurement.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag === 41) {
            message.expectationValues.push(reader.double());

            continue;
          }

          if (tag === 42) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.expectationValues.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.shmDescriptor = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateResponse {
    return {
      stateVector: globalThis.Array.isArray(object?.stateVector)
        ? object.stateVector.map((e: any) => StateResponse_ComplexNumber.fromJSON(e))
        : globalThis.Array.isArray(object?.state_vector)
        ? object.state_vector.map((e: any) => StateResponse_ComplexNumber.fromJSON(e))
        : [],
      classicalResults: isObject(object.classicalResults)
        ? (globalThis.Object.entries(object.classicalResults) as [string, any][]).reduce(
          (acc: { [key: number]: boolean }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : isObject(object.classical_results)
        ? (globalThis.Object.entries(object.classical_results) as [string, any][]).reduce(
          (acc: { [key: number]: boolean }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : {},
      serverId: isSet(object.serverId)
        ? globalThis.String(object.serverId)
        : isSet(object.server_id)
        ? globalThis.String(object.server_id)
        : "",
      sparseStates: globalThis.Array.isArray(object?.sparseStates)
        ? object.sparseStates.map((e: any) => Measurement.fromJSON(e))
        : globalThis.Array.isArray(object?.sparse_states)
        ? object.sparse_states.map((e: any) => Measurement.fromJSON(e))
        : [],
      expectationValues: globalThis.Array.isArray(object?.expectationValues)
        ? object.expectationValues.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.expectation_values)
        ? object.expectation_values.map((e: any) => globalThis.Number(e))
        : [],
      shmDescriptor: isSet(object.shmDescriptor)
        ? globalThis.String(object.shmDescriptor)
        : isSet(object.shm_descriptor)
        ? globalThis.String(object.shm_descriptor)
        : "",
    };
  },

  toJSON(message: StateResponse): unknown {
    const obj: any = {};
    if (message.stateVector?.length) {
      obj.stateVector = message.stateVector.map((e) => StateResponse_ComplexNumber.toJSON(e));
    }
    if (message.classicalResults) {
      const entries = globalThis.Object.entries(message.classicalResults) as [string, boolean][];
      if (entries.length > 0) {
        obj.classicalResults = {};
        entries.forEach(([k, v]) => {
          obj.classicalResults[k] = v;
        });
      }
    }
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.sparseStates?.length) {
      obj.sparseStates = message.sparseStates.map((e) => Measurement.toJSON(e));
    }
    if (message.expectationValues?.length) {
      obj.expectationValues = message.expectationValues;
    }
    if (message.shmDescriptor !== "") {
      obj.shmDescriptor = message.shmDescriptor;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateResponse>, I>>(base?: I): StateResponse {
    return StateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateResponse>, I>>(object: I): StateResponse {
    const message = createBaseStateResponse();
    message.stateVector = object.stateVector?.map((e) => StateResponse_ComplexNumber.fromPartial(e)) || [];
    message.classicalResults = (globalThis.Object.entries(object.classicalResults ?? {}) as [string, boolean][]).reduce(
      (acc: { [key: number]: boolean }, [key, value]: [string, boolean]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    message.serverId = object.serverId ?? "";
    message.sparseStates = object.sparseStates?.map((e) => Measurement.fromPartial(e)) || [];
    message.expectationValues = object.expectationValues?.map((e) => e) || [];
    message.shmDescriptor = object.shmDescriptor ?? "";
    return message;
  },
};

function createBaseStateResponse_ComplexNumber(): StateResponse_ComplexNumber {
  return { real: 0, imag: 0 };
}

export const StateResponse_ComplexNumber: MessageFns<StateResponse_ComplexNumber> = {
  encode(message: StateResponse_ComplexNumber, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.real !== 0) {
      writer.uint32(9).double(message.real);
    }
    if (message.imag !== 0) {
      writer.uint32(17).double(message.imag);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateResponse_ComplexNumber {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateResponse_ComplexNumber();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.real = reader.double();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.imag = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateResponse_ComplexNumber {
    return {
      real: isSet(object.real) ? globalThis.Number(object.real) : 0,
      imag: isSet(object.imag) ? globalThis.Number(object.imag) : 0,
    };
  },

  toJSON(message: StateResponse_ComplexNumber): unknown {
    const obj: any = {};
    if (message.real !== 0) {
      obj.real = message.real;
    }
    if (message.imag !== 0) {
      obj.imag = message.imag;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateResponse_ComplexNumber>, I>>(base?: I): StateResponse_ComplexNumber {
    return StateResponse_ComplexNumber.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateResponse_ComplexNumber>, I>>(object: I): StateResponse_ComplexNumber {
    const message = createBaseStateResponse_ComplexNumber();
    message.real = object.real ?? 0;
    message.imag = object.imag ?? 0;
    return message;
  },
};

function createBaseStateResponse_ClassicalResultsEntry(): StateResponse_ClassicalResultsEntry {
  return { key: 0, value: false };
}

export const StateResponse_ClassicalResultsEntry: MessageFns<StateResponse_ClassicalResultsEntry> = {
  encode(message: StateResponse_ClassicalResultsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).uint32(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateResponse_ClassicalResultsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateResponse_ClassicalResultsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StateResponse_ClassicalResultsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: StateResponse_ClassicalResultsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StateResponse_ClassicalResultsEntry>, I>>(
    base?: I,
  ): StateResponse_ClassicalResultsEntry {
    return StateResponse_ClassicalResultsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StateResponse_ClassicalResultsEntry>, I>>(
    object: I,
  ): StateResponse_ClassicalResultsEntry {
    const message = createBaseStateResponse_ClassicalResultsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseMeasurement(): Measurement {
  return { qubitIndex: 0, result: false, probability: 0 };
}

export const Measurement: MessageFns<Measurement> = {
  encode(message: Measurement, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.qubitIndex !== 0) {
      writer.uint32(8).uint32(message.qubitIndex);
    }
    if (message.result !== false) {
      writer.uint32(16).bool(message.result);
    }
    if (message.probability !== 0) {
      writer.uint32(25).double(message.probability);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Measurement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeasurement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.qubitIndex = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.result = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.probability = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Measurement {
    return {
      qubitIndex: isSet(object.qubitIndex)
        ? globalThis.Number(object.qubitIndex)
        : isSet(object.qubit_index)
        ? globalThis.Number(object.qubit_index)
        : 0,
      result: isSet(object.result) ? globalThis.Boolean(object.result) : false,
      probability: isSet(object.probability) ? globalThis.Number(object.probability) : 0,
    };
  },

  toJSON(message: Measurement): unknown {
    const obj: any = {};
    if (message.qubitIndex !== 0) {
      obj.qubitIndex = Math.round(message.qubitIndex);
    }
    if (message.result !== false) {
      obj.result = message.result;
    }
    if (message.probability !== 0) {
      obj.probability = message.probability;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Measurement>, I>>(base?: I): Measurement {
    return Measurement.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Measurement>, I>>(object: I): Measurement {
    const message = createBaseMeasurement();
    message.qubitIndex = object.qubitIndex ?? 0;
    message.result = object.result ?? false;
    message.probability = object.probability ?? 0;
    return message;
  },
};

function createBasePauliTerm(): PauliTerm {
  return { pauliString: "", coefficient: 0 };
}

export const PauliTerm: MessageFns<PauliTerm> = {
  encode(message: PauliTerm, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pauliString !== "") {
      writer.uint32(10).string(message.pauliString);
    }
    if (message.coefficient !== 0) {
      writer.uint32(17).double(message.coefficient);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PauliTerm {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePauliTerm();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pauliString = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.coefficient = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PauliTerm {
    return {
      pauliString: isSet(object.pauliString)
        ? globalThis.String(object.pauliString)
        : isSet(object.pauli_string)
        ? globalThis.String(object.pauli_string)
        : "",
      coefficient: isSet(object.coefficient) ? globalThis.Number(object.coefficient) : 0,
    };
  },

  toJSON(message: PauliTerm): unknown {
    const obj: any = {};
    if (message.pauliString !== "") {
      obj.pauliString = message.pauliString;
    }
    if (message.coefficient !== 0) {
      obj.coefficient = message.coefficient;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PauliTerm>, I>>(base?: I): PauliTerm {
    return PauliTerm.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PauliTerm>, I>>(object: I): PauliTerm {
    const message = createBasePauliTerm();
    message.pauliString = object.pauliString ?? "";
    message.coefficient = object.coefficient ?? 0;
    return message;
  },
};

function createBaseVQERequest(): VQERequest {
  return { molecule: 0, maxIterations: 0, learningRate: 0, optimizerType: 0, observables: [] };
}

export const VQERequest: MessageFns<VQERequest> = {
  encode(message: VQERequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.molecule !== 0) {
      writer.uint32(8).int32(message.molecule);
    }
    if (message.maxIterations !== 0) {
      writer.uint32(16).int32(message.maxIterations);
    }
    if (message.learningRate !== 0) {
      writer.uint32(25).double(message.learningRate);
    }
    if (message.optimizerType !== 0) {
      writer.uint32(32).int32(message.optimizerType);
    }
    for (const v of message.observables) {
      PauliTerm.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VQERequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVQERequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.molecule = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxIterations = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.learningRate = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.optimizerType = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.observables.push(PauliTerm.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VQERequest {
    return {
      molecule: isSet(object.molecule) ? vQERequest_MoleculeFromJSON(object.molecule) : 0,
      maxIterations: isSet(object.maxIterations)
        ? globalThis.Number(object.maxIterations)
        : isSet(object.max_iterations)
        ? globalThis.Number(object.max_iterations)
        : 0,
      learningRate: isSet(object.learningRate)
        ? globalThis.Number(object.learningRate)
        : isSet(object.learning_rate)
        ? globalThis.Number(object.learning_rate)
        : 0,
      optimizerType: isSet(object.optimizerType)
        ? vQERequest_OptimizerTypeFromJSON(object.optimizerType)
        : isSet(object.optimizer_type)
        ? vQERequest_OptimizerTypeFromJSON(object.optimizer_type)
        : 0,
      observables: globalThis.Array.isArray(object?.observables)
        ? object.observables.map((e: any) => PauliTerm.fromJSON(e))
        : [],
    };
  },

  toJSON(message: VQERequest): unknown {
    const obj: any = {};
    if (message.molecule !== 0) {
      obj.molecule = vQERequest_MoleculeToJSON(message.molecule);
    }
    if (message.maxIterations !== 0) {
      obj.maxIterations = Math.round(message.maxIterations);
    }
    if (message.learningRate !== 0) {
      obj.learningRate = message.learningRate;
    }
    if (message.optimizerType !== 0) {
      obj.optimizerType = vQERequest_OptimizerTypeToJSON(message.optimizerType);
    }
    if (message.observables?.length) {
      obj.observables = message.observables.map((e) => PauliTerm.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VQERequest>, I>>(base?: I): VQERequest {
    return VQERequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VQERequest>, I>>(object: I): VQERequest {
    const message = createBaseVQERequest();
    message.molecule = object.molecule ?? 0;
    message.maxIterations = object.maxIterations ?? 0;
    message.learningRate = object.learningRate ?? 0;
    message.optimizerType = object.optimizerType ?? 0;
    message.observables = object.observables?.map((e) => PauliTerm.fromPartial(e)) || [];
    return message;
  },
};

function createBaseVQEResponse(): VQEResponse {
  return { iteration: 0, energy: 0, parameters: [], converged: false };
}

export const VQEResponse: MessageFns<VQEResponse> = {
  encode(message: VQEResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.iteration !== 0) {
      writer.uint32(8).int32(message.iteration);
    }
    if (message.energy !== 0) {
      writer.uint32(17).double(message.energy);
    }
    writer.uint32(26).fork();
    for (const v of message.parameters) {
      writer.double(v);
    }
    writer.join();
    if (message.converged !== false) {
      writer.uint32(32).bool(message.converged);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VQEResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVQEResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.iteration = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.energy = reader.double();
          continue;
        }
        case 3: {
          if (tag === 25) {
            message.parameters.push(reader.double());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.parameters.push(reader.double());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.converged = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VQEResponse {
    return {
      iteration: isSet(object.iteration) ? globalThis.Number(object.iteration) : 0,
      energy: isSet(object.energy) ? globalThis.Number(object.energy) : 0,
      parameters: globalThis.Array.isArray(object?.parameters)
        ? object.parameters.map((e: any) => globalThis.Number(e))
        : [],
      converged: isSet(object.converged) ? globalThis.Boolean(object.converged) : false,
    };
  },

  toJSON(message: VQEResponse): unknown {
    const obj: any = {};
    if (message.iteration !== 0) {
      obj.iteration = Math.round(message.iteration);
    }
    if (message.energy !== 0) {
      obj.energy = message.energy;
    }
    if (message.parameters?.length) {
      obj.parameters = message.parameters;
    }
    if (message.converged !== false) {
      obj.converged = message.converged;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VQEResponse>, I>>(base?: I): VQEResponse {
    return VQEResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VQEResponse>, I>>(object: I): VQEResponse {
    const message = createBaseVQEResponse();
    message.iteration = object.iteration ?? 0;
    message.energy = object.energy ?? 0;
    message.parameters = object.parameters?.map((e) => e) || [];
    message.converged = object.converged ?? false;
    return message;
  },
};

function createBaseHardwareTopologyRequest(): HardwareTopologyRequest {
  return {};
}

export const HardwareTopologyRequest: MessageFns<HardwareTopologyRequest> = {
  encode(_: HardwareTopologyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HardwareTopologyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHardwareTopologyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HardwareTopologyRequest {
    return {};
  },

  toJSON(_: HardwareTopologyRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HardwareTopologyRequest>, I>>(base?: I): HardwareTopologyRequest {
    return HardwareTopologyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HardwareTopologyRequest>, I>>(_: I): HardwareTopologyRequest {
    const message = createBaseHardwareTopologyRequest();
    return message;
  },
};

function createBaseQubitNode(): QubitNode {
  return { id: 0, x: 0, y: 0 };
}

export const QubitNode: MessageFns<QubitNode> = {
  encode(message: QubitNode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.x !== 0) {
      writer.uint32(17).double(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(25).double(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QubitNode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQubitNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.x = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.y = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QubitNode {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: QubitNode): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QubitNode>, I>>(base?: I): QubitNode {
    return QubitNode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QubitNode>, I>>(object: I): QubitNode {
    const message = createBaseQubitNode();
    message.id = object.id ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

function createBaseCouplerEdge(): CouplerEdge {
  return { node1: 0, node2: 0 };
}

export const CouplerEdge: MessageFns<CouplerEdge> = {
  encode(message: CouplerEdge, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.node1 !== 0) {
      writer.uint32(8).int32(message.node1);
    }
    if (message.node2 !== 0) {
      writer.uint32(16).int32(message.node2);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CouplerEdge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCouplerEdge();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.node1 = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.node2 = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CouplerEdge {
    return {
      node1: isSet(object.node1) ? globalThis.Number(object.node1) : 0,
      node2: isSet(object.node2) ? globalThis.Number(object.node2) : 0,
    };
  },

  toJSON(message: CouplerEdge): unknown {
    const obj: any = {};
    if (message.node1 !== 0) {
      obj.node1 = Math.round(message.node1);
    }
    if (message.node2 !== 0) {
      obj.node2 = Math.round(message.node2);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CouplerEdge>, I>>(base?: I): CouplerEdge {
    return CouplerEdge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CouplerEdge>, I>>(object: I): CouplerEdge {
    const message = createBaseCouplerEdge();
    message.node1 = object.node1 ?? 0;
    message.node2 = object.node2 ?? 0;
    return message;
  },
};

function createBaseHardwareTopologyResponse(): HardwareTopologyResponse {
  return { nodes: [], edges: [] };
}

export const HardwareTopologyResponse: MessageFns<HardwareTopologyResponse> = {
  encode(message: HardwareTopologyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.nodes) {
      QubitNode.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.edges) {
      CouplerEdge.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HardwareTopologyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHardwareTopologyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodes.push(QubitNode.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.edges.push(CouplerEdge.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HardwareTopologyResponse {
    return {
      nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => QubitNode.fromJSON(e)) : [],
      edges: globalThis.Array.isArray(object?.edges) ? object.edges.map((e: any) => CouplerEdge.fromJSON(e)) : [],
    };
  },

  toJSON(message: HardwareTopologyResponse): unknown {
    const obj: any = {};
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => QubitNode.toJSON(e));
    }
    if (message.edges?.length) {
      obj.edges = message.edges.map((e) => CouplerEdge.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HardwareTopologyResponse>, I>>(base?: I): HardwareTopologyResponse {
    return HardwareTopologyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HardwareTopologyResponse>, I>>(object: I): HardwareTopologyResponse {
    const message = createBaseHardwareTopologyResponse();
    message.nodes = object.nodes?.map((e) => QubitNode.fromPartial(e)) || [];
    message.edges = object.edges?.map((e) => CouplerEdge.fromPartial(e)) || [];
    return message;
  },
};

export type QuantumComputeService = typeof QuantumComputeService;
export const QuantumComputeService = {
  /** Synchronous run for small to medium circuits. */
  runCircuit: {
    path: "/qubit_engine.QuantumCompute/RunCircuit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CircuitRequest): Buffer => Buffer.from(CircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CircuitRequest => CircuitRequest.decode(value),
    responseSerialize: (value: StateResponse): Buffer => Buffer.from(StateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StateResponse => StateResponse.decode(value),
  },
  /**
   * Streaming method for large or interactive circuits.
   * Sends a stream of gates and receives a stream of FULL STATE VECTORS.
   *
   * IMPORTANT: the first message MUST be an init message specifying num_qubits.
   */
  streamGates: {
    path: "/qubit_engine.QuantumCompute/StreamGates" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: GateStreamRequest): Buffer => Buffer.from(GateStreamRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GateStreamRequest => GateStreamRequest.decode(value),
    responseSerialize: (value: StateResponse): Buffer => Buffer.from(StateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StateResponse => StateResponse.decode(value),
  },
  /**
   * Visualization method for Web (Server-Side Streaming only).
   * gRPC-Web does not support bidirectional streaming.
   * This executes a circuit and streams back the state after EACH step.
   */
  visualizeCircuit: {
    path: "/qubit_engine.QuantumCompute/VisualizeCircuit" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: CircuitRequest): Buffer => Buffer.from(CircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CircuitRequest => CircuitRequest.decode(value),
    responseSerialize: (value: StateResponse): Buffer => Buffer.from(StateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): StateResponse => StateResponse.decode(value),
  },
  /** VQE Simulation for Quantum Chemistry */
  runVqe: {
    path: "/qubit_engine.QuantumCompute/RunVQE" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: VQERequest): Buffer => Buffer.from(VQERequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): VQERequest => VQERequest.decode(value),
    responseSerialize: (value: VQEResponse): Buffer => Buffer.from(VQEResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VQEResponse => VQEResponse.decode(value),
  },
  /** Fetch Hardware Topology for Visualization */
  getHardwareTopology: {
    path: "/qubit_engine.QuantumCompute/GetHardwareTopology" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HardwareTopologyRequest): Buffer =>
      Buffer.from(HardwareTopologyRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HardwareTopologyRequest => HardwareTopologyRequest.decode(value),
    responseSerialize: (value: HardwareTopologyResponse): Buffer =>
      Buffer.from(HardwareTopologyResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HardwareTopologyResponse => HardwareTopologyResponse.decode(value),
  },
} as const;

export interface QuantumComputeServer extends UntypedServiceImplementation {
  /** Synchronous run for small to medium circuits. */
  runCircuit: handleUnaryCall<CircuitRequest, StateResponse>;
  /**
   * Streaming method for large or interactive circuits.
   * Sends a stream of gates and receives a stream of FULL STATE VECTORS.
   *
   * IMPORTANT: the first message MUST be an init message specifying num_qubits.
   */
  streamGates: handleBidiStreamingCall<GateStreamRequest, StateResponse>;
  /**
   * Visualization method for Web (Server-Side Streaming only).
   * gRPC-Web does not support bidirectional streaming.
   * This executes a circuit and streams back the state after EACH step.
   */
  visualizeCircuit: handleServerStreamingCall<CircuitRequest, StateResponse>;
  /** VQE Simulation for Quantum Chemistry */
  runVqe: handleServerStreamingCall<VQERequest, VQEResponse>;
  /** Fetch Hardware Topology for Visualization */
  getHardwareTopology: handleUnaryCall<HardwareTopologyRequest, HardwareTopologyResponse>;
}

export interface QuantumComputeClient extends Client {
  /** Synchronous run for small to medium circuits. */
  runCircuit(
    request: CircuitRequest,
    callback: (error: ServiceError | null, response: StateResponse) => void,
  ): ClientUnaryCall;
  runCircuit(
    request: CircuitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: StateResponse) => void,
  ): ClientUnaryCall;
  runCircuit(
    request: CircuitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: StateResponse) => void,
  ): ClientUnaryCall;
  /**
   * Streaming method for large or interactive circuits.
   * Sends a stream of gates and receives a stream of FULL STATE VECTORS.
   *
   * IMPORTANT: the first message MUST be an init message specifying num_qubits.
   */
  streamGates(): ClientDuplexStream<GateStreamRequest, StateResponse>;
  streamGates(options: Partial<CallOptions>): ClientDuplexStream<GateStreamRequest, StateResponse>;
  streamGates(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<GateStreamRequest, StateResponse>;
  /**
   * Visualization method for Web (Server-Side Streaming only).
   * gRPC-Web does not support bidirectional streaming.
   * This executes a circuit and streams back the state after EACH step.
   */
  visualizeCircuit(request: CircuitRequest, options?: Partial<CallOptions>): ClientReadableStream<StateResponse>;
  visualizeCircuit(
    request: CircuitRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<StateResponse>;
  /** VQE Simulation for Quantum Chemistry */
  runVqe(request: VQERequest, options?: Partial<CallOptions>): ClientReadableStream<VQEResponse>;
  runVqe(request: VQERequest, metadata?: Metadata, options?: Partial<CallOptions>): ClientReadableStream<VQEResponse>;
  /** Fetch Hardware Topology for Visualization */
  getHardwareTopology(
    request: HardwareTopologyRequest,
    callback: (error: ServiceError | null, response: HardwareTopologyResponse) => void,
  ): ClientUnaryCall;
  getHardwareTopology(
    request: HardwareTopologyRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: HardwareTopologyResponse) => void,
  ): ClientUnaryCall;
  getHardwareTopology(
    request: HardwareTopologyRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: HardwareTopologyResponse) => void,
  ): ClientUnaryCall;
}

export const QuantumComputeClient = makeGenericClientConstructor(
  QuantumComputeService,
  "qubit_engine.QuantumCompute",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): QuantumComputeClient;
  service: typeof QuantumComputeService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
