// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v5.29.5
// source: api/proto/registry.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { CircuitRequest } from "./quantum";

export const protobufPackage = "qubit_engine";

export interface SaveCircuitRequest {
  name: string;
  description: string;
  circuit:
    | CircuitRequest
    | undefined;
  /** "physics", "finance", "education", "chemistry", "crypto" */
  domain: string;
  tags: string[];
  isPublic: boolean;
}

export interface LoadCircuitRequest {
  circuitId: string;
  /** 0 = latest */
  version: number;
}

export interface ListCircuitsRequest {
  /** Filter by domain */
  domain: string;
  /** Filter by tags (AND) */
  tags: string[];
  /** Filter by author */
  author: string;
  publicOnly: boolean;
  page: number;
  pageSize: number;
}

export interface ForkCircuitRequest {
  sourceCircuitId: string;
  newName: string;
}

export interface DeleteCircuitRequest {
  circuitId: string;
}

export interface CircuitMetadata {
  id: string;
  name: string;
  description: string;
  author: string;
  domain: string;
  tags: string[];
  numQubits: number;
  numOperations: number;
  version: number;
  /** Unix timestamp */
  createdAt: number;
  updatedAt: number;
  isPublic: boolean;
  forkCount: number;
  runCount: number;
}

export interface CircuitList {
  circuits: CircuitMetadata[];
  totalCount: number;
  page: number;
  pageSize: number;
}

export interface RegistryEmpty {
}

function createBaseSaveCircuitRequest(): SaveCircuitRequest {
  return { name: "", description: "", circuit: undefined, domain: "", tags: [], isPublic: false };
}

export const SaveCircuitRequest: MessageFns<SaveCircuitRequest> = {
  encode(message: SaveCircuitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.circuit !== undefined) {
      CircuitRequest.encode(message.circuit, writer.uint32(26).fork()).join();
    }
    if (message.domain !== "") {
      writer.uint32(34).string(message.domain);
    }
    for (const v of message.tags) {
      writer.uint32(42).string(v!);
    }
    if (message.isPublic !== false) {
      writer.uint32(48).bool(message.isPublic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SaveCircuitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSaveCircuitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.circuit = CircuitRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SaveCircuitRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      circuit: isSet(object.circuit) ? CircuitRequest.fromJSON(object.circuit) : undefined,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      isPublic: isSet(object.isPublic)
        ? globalThis.Boolean(object.isPublic)
        : isSet(object.is_public)
        ? globalThis.Boolean(object.is_public)
        : false,
    };
  },

  toJSON(message: SaveCircuitRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.circuit !== undefined) {
      obj.circuit = CircuitRequest.toJSON(message.circuit);
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SaveCircuitRequest>, I>>(base?: I): SaveCircuitRequest {
    return SaveCircuitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SaveCircuitRequest>, I>>(object: I): SaveCircuitRequest {
    const message = createBaseSaveCircuitRequest();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.circuit = (object.circuit !== undefined && object.circuit !== null)
      ? CircuitRequest.fromPartial(object.circuit)
      : undefined;
    message.domain = object.domain ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    message.isPublic = object.isPublic ?? false;
    return message;
  },
};

function createBaseLoadCircuitRequest(): LoadCircuitRequest {
  return { circuitId: "", version: 0 };
}

export const LoadCircuitRequest: MessageFns<LoadCircuitRequest> = {
  encode(message: LoadCircuitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuitId !== "") {
      writer.uint32(10).string(message.circuitId);
    }
    if (message.version !== 0) {
      writer.uint32(16).int32(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoadCircuitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoadCircuitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuitId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoadCircuitRequest {
    return {
      circuitId: isSet(object.circuitId)
        ? globalThis.String(object.circuitId)
        : isSet(object.circuit_id)
        ? globalThis.String(object.circuit_id)
        : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: LoadCircuitRequest): unknown {
    const obj: any = {};
    if (message.circuitId !== "") {
      obj.circuitId = message.circuitId;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoadCircuitRequest>, I>>(base?: I): LoadCircuitRequest {
    return LoadCircuitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoadCircuitRequest>, I>>(object: I): LoadCircuitRequest {
    const message = createBaseLoadCircuitRequest();
    message.circuitId = object.circuitId ?? "";
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseListCircuitsRequest(): ListCircuitsRequest {
  return { domain: "", tags: [], author: "", publicOnly: false, page: 0, pageSize: 0 };
}

export const ListCircuitsRequest: MessageFns<ListCircuitsRequest> = {
  encode(message: ListCircuitsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domain !== "") {
      writer.uint32(10).string(message.domain);
    }
    for (const v of message.tags) {
      writer.uint32(18).string(v!);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.publicOnly !== false) {
      writer.uint32(32).bool(message.publicOnly);
    }
    if (message.page !== 0) {
      writer.uint32(40).int32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(48).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListCircuitsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListCircuitsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.publicOnly = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListCircuitsRequest {
    return {
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      publicOnly: isSet(object.publicOnly)
        ? globalThis.Boolean(object.publicOnly)
        : isSet(object.public_only)
        ? globalThis.Boolean(object.public_only)
        : false,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
    };
  },

  toJSON(message: ListCircuitsRequest): unknown {
    const obj: any = {};
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.publicOnly !== false) {
      obj.publicOnly = message.publicOnly;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListCircuitsRequest>, I>>(base?: I): ListCircuitsRequest {
    return ListCircuitsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListCircuitsRequest>, I>>(object: I): ListCircuitsRequest {
    const message = createBaseListCircuitsRequest();
    message.domain = object.domain ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    message.author = object.author ?? "";
    message.publicOnly = object.publicOnly ?? false;
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseForkCircuitRequest(): ForkCircuitRequest {
  return { sourceCircuitId: "", newName: "" };
}

export const ForkCircuitRequest: MessageFns<ForkCircuitRequest> = {
  encode(message: ForkCircuitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sourceCircuitId !== "") {
      writer.uint32(10).string(message.sourceCircuitId);
    }
    if (message.newName !== "") {
      writer.uint32(18).string(message.newName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ForkCircuitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseForkCircuitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sourceCircuitId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ForkCircuitRequest {
    return {
      sourceCircuitId: isSet(object.sourceCircuitId)
        ? globalThis.String(object.sourceCircuitId)
        : isSet(object.source_circuit_id)
        ? globalThis.String(object.source_circuit_id)
        : "",
      newName: isSet(object.newName)
        ? globalThis.String(object.newName)
        : isSet(object.new_name)
        ? globalThis.String(object.new_name)
        : "",
    };
  },

  toJSON(message: ForkCircuitRequest): unknown {
    const obj: any = {};
    if (message.sourceCircuitId !== "") {
      obj.sourceCircuitId = message.sourceCircuitId;
    }
    if (message.newName !== "") {
      obj.newName = message.newName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ForkCircuitRequest>, I>>(base?: I): ForkCircuitRequest {
    return ForkCircuitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ForkCircuitRequest>, I>>(object: I): ForkCircuitRequest {
    const message = createBaseForkCircuitRequest();
    message.sourceCircuitId = object.sourceCircuitId ?? "";
    message.newName = object.newName ?? "";
    return message;
  },
};

function createBaseDeleteCircuitRequest(): DeleteCircuitRequest {
  return { circuitId: "" };
}

export const DeleteCircuitRequest: MessageFns<DeleteCircuitRequest> = {
  encode(message: DeleteCircuitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuitId !== "") {
      writer.uint32(10).string(message.circuitId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteCircuitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteCircuitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuitId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteCircuitRequest {
    return {
      circuitId: isSet(object.circuitId)
        ? globalThis.String(object.circuitId)
        : isSet(object.circuit_id)
        ? globalThis.String(object.circuit_id)
        : "",
    };
  },

  toJSON(message: DeleteCircuitRequest): unknown {
    const obj: any = {};
    if (message.circuitId !== "") {
      obj.circuitId = message.circuitId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteCircuitRequest>, I>>(base?: I): DeleteCircuitRequest {
    return DeleteCircuitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteCircuitRequest>, I>>(object: I): DeleteCircuitRequest {
    const message = createBaseDeleteCircuitRequest();
    message.circuitId = object.circuitId ?? "";
    return message;
  },
};

function createBaseCircuitMetadata(): CircuitMetadata {
  return {
    id: "",
    name: "",
    description: "",
    author: "",
    domain: "",
    tags: [],
    numQubits: 0,
    numOperations: 0,
    version: 0,
    createdAt: 0,
    updatedAt: 0,
    isPublic: false,
    forkCount: 0,
    runCount: 0,
  };
}

export const CircuitMetadata: MessageFns<CircuitMetadata> = {
  encode(message: CircuitMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.author !== "") {
      writer.uint32(34).string(message.author);
    }
    if (message.domain !== "") {
      writer.uint32(42).string(message.domain);
    }
    for (const v of message.tags) {
      writer.uint32(50).string(v!);
    }
    if (message.numQubits !== 0) {
      writer.uint32(56).int32(message.numQubits);
    }
    if (message.numOperations !== 0) {
      writer.uint32(64).int32(message.numOperations);
    }
    if (message.version !== 0) {
      writer.uint32(72).int32(message.version);
    }
    if (message.createdAt !== 0) {
      writer.uint32(80).int64(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      writer.uint32(88).int64(message.updatedAt);
    }
    if (message.isPublic !== false) {
      writer.uint32(96).bool(message.isPublic);
    }
    if (message.forkCount !== 0) {
      writer.uint32(104).int32(message.forkCount);
    }
    if (message.runCount !== 0) {
      writer.uint32(112).int32(message.runCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CircuitMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCircuitMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.numQubits = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.numOperations = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.updatedAt = longToNumber(reader.int64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.forkCount = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.runCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CircuitMetadata {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      numQubits: isSet(object.numQubits)
        ? globalThis.Number(object.numQubits)
        : isSet(object.num_qubits)
        ? globalThis.Number(object.num_qubits)
        : 0,
      numOperations: isSet(object.numOperations)
        ? globalThis.Number(object.numOperations)
        : isSet(object.num_operations)
        ? globalThis.Number(object.num_operations)
        : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      updatedAt: isSet(object.updatedAt)
        ? globalThis.Number(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.Number(object.updated_at)
        : 0,
      isPublic: isSet(object.isPublic)
        ? globalThis.Boolean(object.isPublic)
        : isSet(object.is_public)
        ? globalThis.Boolean(object.is_public)
        : false,
      forkCount: isSet(object.forkCount)
        ? globalThis.Number(object.forkCount)
        : isSet(object.fork_count)
        ? globalThis.Number(object.fork_count)
        : 0,
      runCount: isSet(object.runCount)
        ? globalThis.Number(object.runCount)
        : isSet(object.run_count)
        ? globalThis.Number(object.run_count)
        : 0,
    };
  },

  toJSON(message: CircuitMetadata): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.numQubits !== 0) {
      obj.numQubits = Math.round(message.numQubits);
    }
    if (message.numOperations !== 0) {
      obj.numOperations = Math.round(message.numOperations);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.updatedAt !== 0) {
      obj.updatedAt = Math.round(message.updatedAt);
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    if (message.forkCount !== 0) {
      obj.forkCount = Math.round(message.forkCount);
    }
    if (message.runCount !== 0) {
      obj.runCount = Math.round(message.runCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CircuitMetadata>, I>>(base?: I): CircuitMetadata {
    return CircuitMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CircuitMetadata>, I>>(object: I): CircuitMetadata {
    const message = createBaseCircuitMetadata();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.author = object.author ?? "";
    message.domain = object.domain ?? "";
    message.tags = object.tags?.map((e) => e) || [];
    message.numQubits = object.numQubits ?? 0;
    message.numOperations = object.numOperations ?? 0;
    message.version = object.version ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.updatedAt = object.updatedAt ?? 0;
    message.isPublic = object.isPublic ?? false;
    message.forkCount = object.forkCount ?? 0;
    message.runCount = object.runCount ?? 0;
    return message;
  },
};

function createBaseCircuitList(): CircuitList {
  return { circuits: [], totalCount: 0, page: 0, pageSize: 0 };
}

export const CircuitList: MessageFns<CircuitList> = {
  encode(message: CircuitList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.circuits) {
      CircuitMetadata.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalCount !== 0) {
      writer.uint32(16).int32(message.totalCount);
    }
    if (message.page !== 0) {
      writer.uint32(24).int32(message.page);
    }
    if (message.pageSize !== 0) {
      writer.uint32(32).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CircuitList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCircuitList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuits.push(CircuitMetadata.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CircuitList {
    return {
      circuits: globalThis.Array.isArray(object?.circuits)
        ? object.circuits.map((e: any) => CircuitMetadata.fromJSON(e))
        : [],
      totalCount: isSet(object.totalCount)
        ? globalThis.Number(object.totalCount)
        : isSet(object.total_count)
        ? globalThis.Number(object.total_count)
        : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
    };
  },

  toJSON(message: CircuitList): unknown {
    const obj: any = {};
    if (message.circuits?.length) {
      obj.circuits = message.circuits.map((e) => CircuitMetadata.toJSON(e));
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CircuitList>, I>>(base?: I): CircuitList {
    return CircuitList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CircuitList>, I>>(object: I): CircuitList {
    const message = createBaseCircuitList();
    message.circuits = object.circuits?.map((e) => CircuitMetadata.fromPartial(e)) || [];
    message.totalCount = object.totalCount ?? 0;
    message.page = object.page ?? 0;
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseRegistryEmpty(): RegistryEmpty {
  return {};
}

export const RegistryEmpty: MessageFns<RegistryEmpty> = {
  encode(_: RegistryEmpty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegistryEmpty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegistryEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RegistryEmpty {
    return {};
  },

  toJSON(_: RegistryEmpty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RegistryEmpty>, I>>(base?: I): RegistryEmpty {
    return RegistryEmpty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegistryEmpty>, I>>(_: I): RegistryEmpty {
    const message = createBaseRegistryEmpty();
    return message;
  },
};

export type CircuitRegistryService = typeof CircuitRegistryService;
export const CircuitRegistryService = {
  /** Save a circuit to the registry */
  saveCircuit: {
    path: "/qubit_engine.CircuitRegistry/SaveCircuit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SaveCircuitRequest): Buffer => Buffer.from(SaveCircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SaveCircuitRequest => SaveCircuitRequest.decode(value),
    responseSerialize: (value: CircuitMetadata): Buffer => Buffer.from(CircuitMetadata.encode(value).finish()),
    responseDeserialize: (value: Buffer): CircuitMetadata => CircuitMetadata.decode(value),
  },
  /** Load a circuit by ID */
  loadCircuit: {
    path: "/qubit_engine.CircuitRegistry/LoadCircuit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: LoadCircuitRequest): Buffer => Buffer.from(LoadCircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LoadCircuitRequest => LoadCircuitRequest.decode(value),
    responseSerialize: (value: CircuitRequest): Buffer => Buffer.from(CircuitRequest.encode(value).finish()),
    responseDeserialize: (value: Buffer): CircuitRequest => CircuitRequest.decode(value),
  },
  /** List circuits with optional filters */
  listCircuits: {
    path: "/qubit_engine.CircuitRegistry/ListCircuits" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListCircuitsRequest): Buffer => Buffer.from(ListCircuitsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListCircuitsRequest => ListCircuitsRequest.decode(value),
    responseSerialize: (value: CircuitList): Buffer => Buffer.from(CircuitList.encode(value).finish()),
    responseDeserialize: (value: Buffer): CircuitList => CircuitList.decode(value),
  },
  /** Fork (copy) an existing circuit for modification */
  forkCircuit: {
    path: "/qubit_engine.CircuitRegistry/ForkCircuit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ForkCircuitRequest): Buffer => Buffer.from(ForkCircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ForkCircuitRequest => ForkCircuitRequest.decode(value),
    responseSerialize: (value: CircuitMetadata): Buffer => Buffer.from(CircuitMetadata.encode(value).finish()),
    responseDeserialize: (value: Buffer): CircuitMetadata => CircuitMetadata.decode(value),
  },
  /** Delete a circuit (owner only) */
  deleteCircuit: {
    path: "/qubit_engine.CircuitRegistry/DeleteCircuit" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteCircuitRequest): Buffer => Buffer.from(DeleteCircuitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteCircuitRequest => DeleteCircuitRequest.decode(value),
    responseSerialize: (value: RegistryEmpty): Buffer => Buffer.from(RegistryEmpty.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegistryEmpty => RegistryEmpty.decode(value),
  },
} as const;

export interface CircuitRegistryServer extends UntypedServiceImplementation {
  /** Save a circuit to the registry */
  saveCircuit: handleUnaryCall<SaveCircuitRequest, CircuitMetadata>;
  /** Load a circuit by ID */
  loadCircuit: handleUnaryCall<LoadCircuitRequest, CircuitRequest>;
  /** List circuits with optional filters */
  listCircuits: handleUnaryCall<ListCircuitsRequest, CircuitList>;
  /** Fork (copy) an existing circuit for modification */
  forkCircuit: handleUnaryCall<ForkCircuitRequest, CircuitMetadata>;
  /** Delete a circuit (owner only) */
  deleteCircuit: handleUnaryCall<DeleteCircuitRequest, RegistryEmpty>;
}

export interface CircuitRegistryClient extends Client {
  /** Save a circuit to the registry */
  saveCircuit(
    request: SaveCircuitRequest,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  saveCircuit(
    request: SaveCircuitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  saveCircuit(
    request: SaveCircuitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  /** Load a circuit by ID */
  loadCircuit(
    request: LoadCircuitRequest,
    callback: (error: ServiceError | null, response: CircuitRequest) => void,
  ): ClientUnaryCall;
  loadCircuit(
    request: LoadCircuitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CircuitRequest) => void,
  ): ClientUnaryCall;
  loadCircuit(
    request: LoadCircuitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CircuitRequest) => void,
  ): ClientUnaryCall;
  /** List circuits with optional filters */
  listCircuits(
    request: ListCircuitsRequest,
    callback: (error: ServiceError | null, response: CircuitList) => void,
  ): ClientUnaryCall;
  listCircuits(
    request: ListCircuitsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CircuitList) => void,
  ): ClientUnaryCall;
  listCircuits(
    request: ListCircuitsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CircuitList) => void,
  ): ClientUnaryCall;
  /** Fork (copy) an existing circuit for modification */
  forkCircuit(
    request: ForkCircuitRequest,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  forkCircuit(
    request: ForkCircuitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  forkCircuit(
    request: ForkCircuitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CircuitMetadata) => void,
  ): ClientUnaryCall;
  /** Delete a circuit (owner only) */
  deleteCircuit(
    request: DeleteCircuitRequest,
    callback: (error: ServiceError | null, response: RegistryEmpty) => void,
  ): ClientUnaryCall;
  deleteCircuit(
    request: DeleteCircuitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RegistryEmpty) => void,
  ): ClientUnaryCall;
  deleteCircuit(
    request: DeleteCircuitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RegistryEmpty) => void,
  ): ClientUnaryCall;
}

export const CircuitRegistryClient = makeGenericClientConstructor(
  CircuitRegistryService,
  "qubit_engine.CircuitRegistry",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): CircuitRegistryClient;
  service: typeof CircuitRegistryService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
