// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.19.1
// source: api/proto/scheduler.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
export interface Empty {}
export const Empty: any = {
  encode: () => ({ finish: () => new Uint8Array() }),
  decode: () => ({})
};
import { CircuitRequest, StateResponse } from "./quantum";

export const protobufPackage = "qubit_engine";

export enum JobPriority {
  PRIORITY_LOW = 0,
  PRIORITY_NORMAL = 1,
  PRIORITY_HIGH = 2,
  PRIORITY_REALTIME = 3,
  UNRECOGNIZED = -1,
}

export function jobPriorityFromJSON(object: any): JobPriority {
  switch (object) {
    case 0:
    case "PRIORITY_LOW":
      return JobPriority.PRIORITY_LOW;
    case 1:
    case "PRIORITY_NORMAL":
      return JobPriority.PRIORITY_NORMAL;
    case 2:
    case "PRIORITY_HIGH":
      return JobPriority.PRIORITY_HIGH;
    case 3:
    case "PRIORITY_REALTIME":
      return JobPriority.PRIORITY_REALTIME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JobPriority.UNRECOGNIZED;
  }
}

export function jobPriorityToJSON(object: JobPriority): string {
  switch (object) {
    case JobPriority.PRIORITY_LOW:
      return "PRIORITY_LOW";
    case JobPriority.PRIORITY_NORMAL:
      return "PRIORITY_NORMAL";
    case JobPriority.PRIORITY_HIGH:
      return "PRIORITY_HIGH";
    case JobPriority.PRIORITY_REALTIME:
      return "PRIORITY_REALTIME";
    case JobPriority.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum JobState {
  STATE_UNKNOWN = 0,
  STATE_QUEUED = 1,
  STATE_RUNNING = 2,
  STATE_COMPLETED = 3,
  STATE_FAILED = 4,
  STATE_CANCELLED = 5,
  UNRECOGNIZED = -1,
}

export function jobStateFromJSON(object: any): JobState {
  switch (object) {
    case 0:
    case "STATE_UNKNOWN":
      return JobState.STATE_UNKNOWN;
    case 1:
    case "STATE_QUEUED":
      return JobState.STATE_QUEUED;
    case 2:
    case "STATE_RUNNING":
      return JobState.STATE_RUNNING;
    case 3:
    case "STATE_COMPLETED":
      return JobState.STATE_COMPLETED;
    case 4:
    case "STATE_FAILED":
      return JobState.STATE_FAILED;
    case 5:
    case "STATE_CANCELLED":
      return JobState.STATE_CANCELLED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JobState.UNRECOGNIZED;
  }
}

export function jobStateToJSON(object: JobState): string {
  switch (object) {
    case JobState.STATE_UNKNOWN:
      return "STATE_UNKNOWN";
    case JobState.STATE_QUEUED:
      return "STATE_QUEUED";
    case JobState.STATE_RUNNING:
      return "STATE_RUNNING";
    case JobState.STATE_COMPLETED:
      return "STATE_COMPLETED";
    case JobState.STATE_FAILED:
      return "STATE_FAILED";
    case JobState.STATE_CANCELLED:
      return "STATE_CANCELLED";
    case JobState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface JobRequest {
  circuit: CircuitRequest | undefined;
  priority: JobPriority;
  /** Number of measurement repetitions */
  shots: number;
  /** Optional webhook for completion notification */
  callbackUrl: string;
  /** User/tenant identifier */
  userId: string;
  /** Custom metadata */
  metadata: { [key: string]: string };
}

export interface JobRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface JobHandle {
  jobId: string;
  /** Unix timestamp */
  submittedAt: number;
  estimatedWaitSeconds: number;
}

export interface JobStatus {
  jobId: string;
  state: JobState;
  /** 0 if running or completed */
  positionInQueue: number;
  /** 0-100 */
  progressPercent: number;
  /** Which engine pod is processing */
  workerId: string;
  startedAt: number;
  completedAt: number;
  /** Set if state == FAILED */
  errorMessage: string;
}

export interface CancelResponse {
  success: boolean;
  message: string;
}

export interface JobResult {
  jobId: string;
  /** Which shot (1 to N) */
  shotNumber: number;
  /** The quantum state after circuit */
  state:
    | StateResponse
    | undefined;
  /** Qubit -> measurement result */
  measurements: { [key: number]: boolean };
}

export interface JobResult_MeasurementsEntry {
  key: number;
  value: boolean;
}

export interface ListJobsRequest {
  userId: string;
  /** Optional, 0 = all states */
  stateFilter: JobState;
  limit: number;
  offset: number;
}

export interface JobList {
  jobs: JobStatus[];
  totalCount: number;
}

export interface ClusterMetricsResponse {
  activeWorkers: number;
  queueDepth: number;
  memoryUsagePercent: number;
  /** Map JobState to count */
  jobsByState: { [key: number]: number };
}

export interface ClusterMetricsResponse_JobsByStateEntry {
  key: number;
  value: number;
}

function createBaseJobRequest(): JobRequest {
  return { circuit: undefined, priority: 0, shots: 0, callbackUrl: "", userId: "", metadata: {} };
}

export const JobRequest: MessageFns<JobRequest> = {
  encode(message: JobRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuit !== undefined) {
      CircuitRequest.encode(message.circuit, writer.uint32(10).fork()).join();
    }
    if (message.priority !== 0) {
      writer.uint32(16).int32(message.priority);
    }
    if (message.shots !== 0) {
      writer.uint32(24).int32(message.shots);
    }
    if (message.callbackUrl !== "") {
      writer.uint32(34).string(message.callbackUrl);
    }
    if (message.userId !== "") {
      writer.uint32(42).string(message.userId);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      JobRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuit = CircuitRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.priority = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.shots = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.callbackUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = JobRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.metadata[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobRequest {
    return {
      circuit: isSet(object.circuit) ? CircuitRequest.fromJSON(object.circuit) : undefined,
      priority: isSet(object.priority) ? jobPriorityFromJSON(object.priority) : 0,
      shots: isSet(object.shots) ? globalThis.Number(object.shots) : 0,
      callbackUrl: isSet(object.callbackUrl)
        ? globalThis.String(object.callbackUrl)
        : isSet(object.callback_url)
        ? globalThis.String(object.callback_url)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: JobRequest): unknown {
    const obj: any = {};
    if (message.circuit !== undefined) {
      obj.circuit = CircuitRequest.toJSON(message.circuit);
    }
    if (message.priority !== 0) {
      obj.priority = jobPriorityToJSON(message.priority);
    }
    if (message.shots !== 0) {
      obj.shots = Math.round(message.shots);
    }
    if (message.callbackUrl !== "") {
      obj.callbackUrl = message.callbackUrl;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobRequest>, I>>(base?: I): JobRequest {
    return JobRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobRequest>, I>>(object: I): JobRequest {
    const message = createBaseJobRequest();
    message.circuit = (object.circuit !== undefined && object.circuit !== null)
      ? CircuitRequest.fromPartial(object.circuit)
      : undefined;
    message.priority = object.priority ?? 0;
    message.shots = object.shots ?? 0;
    message.callbackUrl = object.callbackUrl ?? "";
    message.userId = object.userId ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseJobRequest_MetadataEntry(): JobRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const JobRequest_MetadataEntry: MessageFns<JobRequest_MetadataEntry> = {
  encode(message: JobRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: JobRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobRequest_MetadataEntry>, I>>(base?: I): JobRequest_MetadataEntry {
    return JobRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobRequest_MetadataEntry>, I>>(object: I): JobRequest_MetadataEntry {
    const message = createBaseJobRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseJobHandle(): JobHandle {
  return { jobId: "", submittedAt: 0, estimatedWaitSeconds: 0 };
}

export const JobHandle: MessageFns<JobHandle> = {
  encode(message: JobHandle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.submittedAt !== 0) {
      writer.uint32(16).int64(message.submittedAt);
    }
    if (message.estimatedWaitSeconds !== 0) {
      writer.uint32(24).int32(message.estimatedWaitSeconds);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobHandle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobHandle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.submittedAt = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.estimatedWaitSeconds = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobHandle {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      submittedAt: isSet(object.submittedAt)
        ? globalThis.Number(object.submittedAt)
        : isSet(object.submitted_at)
        ? globalThis.Number(object.submitted_at)
        : 0,
      estimatedWaitSeconds: isSet(object.estimatedWaitSeconds)
        ? globalThis.Number(object.estimatedWaitSeconds)
        : isSet(object.estimated_wait_seconds)
        ? globalThis.Number(object.estimated_wait_seconds)
        : 0,
    };
  },

  toJSON(message: JobHandle): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.submittedAt !== 0) {
      obj.submittedAt = Math.round(message.submittedAt);
    }
    if (message.estimatedWaitSeconds !== 0) {
      obj.estimatedWaitSeconds = Math.round(message.estimatedWaitSeconds);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobHandle>, I>>(base?: I): JobHandle {
    return JobHandle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobHandle>, I>>(object: I): JobHandle {
    const message = createBaseJobHandle();
    message.jobId = object.jobId ?? "";
    message.submittedAt = object.submittedAt ?? 0;
    message.estimatedWaitSeconds = object.estimatedWaitSeconds ?? 0;
    return message;
  },
};

function createBaseJobStatus(): JobStatus {
  return {
    jobId: "",
    state: 0,
    positionInQueue: 0,
    progressPercent: 0,
    workerId: "",
    startedAt: 0,
    completedAt: 0,
    errorMessage: "",
  };
}

export const JobStatus: MessageFns<JobStatus> = {
  encode(message: JobStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.state !== 0) {
      writer.uint32(16).int32(message.state);
    }
    if (message.positionInQueue !== 0) {
      writer.uint32(24).int32(message.positionInQueue);
    }
    if (message.progressPercent !== 0) {
      writer.uint32(32).int32(message.progressPercent);
    }
    if (message.workerId !== "") {
      writer.uint32(42).string(message.workerId);
    }
    if (message.startedAt !== 0) {
      writer.uint32(48).int64(message.startedAt);
    }
    if (message.completedAt !== 0) {
      writer.uint32(56).int64(message.completedAt);
    }
    if (message.errorMessage !== "") {
      writer.uint32(66).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.state = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.positionInQueue = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.progressPercent = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.workerId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.startedAt = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.completedAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobStatus {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      state: isSet(object.state) ? jobStateFromJSON(object.state) : 0,
      positionInQueue: isSet(object.positionInQueue)
        ? globalThis.Number(object.positionInQueue)
        : isSet(object.position_in_queue)
        ? globalThis.Number(object.position_in_queue)
        : 0,
      progressPercent: isSet(object.progressPercent)
        ? globalThis.Number(object.progressPercent)
        : isSet(object.progress_percent)
        ? globalThis.Number(object.progress_percent)
        : 0,
      workerId: isSet(object.workerId)
        ? globalThis.String(object.workerId)
        : isSet(object.worker_id)
        ? globalThis.String(object.worker_id)
        : "",
      startedAt: isSet(object.startedAt)
        ? globalThis.Number(object.startedAt)
        : isSet(object.started_at)
        ? globalThis.Number(object.started_at)
        : 0,
      completedAt: isSet(object.completedAt)
        ? globalThis.Number(object.completedAt)
        : isSet(object.completed_at)
        ? globalThis.Number(object.completed_at)
        : 0,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: JobStatus): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.state !== 0) {
      obj.state = jobStateToJSON(message.state);
    }
    if (message.positionInQueue !== 0) {
      obj.positionInQueue = Math.round(message.positionInQueue);
    }
    if (message.progressPercent !== 0) {
      obj.progressPercent = Math.round(message.progressPercent);
    }
    if (message.workerId !== "") {
      obj.workerId = message.workerId;
    }
    if (message.startedAt !== 0) {
      obj.startedAt = Math.round(message.startedAt);
    }
    if (message.completedAt !== 0) {
      obj.completedAt = Math.round(message.completedAt);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobStatus>, I>>(base?: I): JobStatus {
    return JobStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobStatus>, I>>(object: I): JobStatus {
    const message = createBaseJobStatus();
    message.jobId = object.jobId ?? "";
    message.state = object.state ?? 0;
    message.positionInQueue = object.positionInQueue ?? 0;
    message.progressPercent = object.progressPercent ?? 0;
    message.workerId = object.workerId ?? "";
    message.startedAt = object.startedAt ?? 0;
    message.completedAt = object.completedAt ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseCancelResponse(): CancelResponse {
  return { success: false, message: "" };
}

export const CancelResponse: MessageFns<CancelResponse> = {
  encode(message: CancelResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: CancelResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelResponse>, I>>(base?: I): CancelResponse {
    return CancelResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelResponse>, I>>(object: I): CancelResponse {
    const message = createBaseCancelResponse();
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseJobResult(): JobResult {
  return { jobId: "", shotNumber: 0, state: undefined, measurements: {} };
}

export const JobResult: MessageFns<JobResult> = {
  encode(message: JobResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.jobId !== "") {
      writer.uint32(10).string(message.jobId);
    }
    if (message.shotNumber !== 0) {
      writer.uint32(16).int32(message.shotNumber);
    }
    if (message.state !== undefined) {
      StateResponse.encode(message.state, writer.uint32(26).fork()).join();
    }
    globalThis.Object.entries(message.measurements).forEach(([key, value]: [string, boolean]) => {
      JobResult_MeasurementsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shotNumber = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.state = StateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = JobResult_MeasurementsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.measurements[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobResult {
    return {
      jobId: isSet(object.jobId)
        ? globalThis.String(object.jobId)
        : isSet(object.job_id)
        ? globalThis.String(object.job_id)
        : "",
      shotNumber: isSet(object.shotNumber)
        ? globalThis.Number(object.shotNumber)
        : isSet(object.shot_number)
        ? globalThis.Number(object.shot_number)
        : 0,
      state: isSet(object.state) ? StateResponse.fromJSON(object.state) : undefined,
      measurements: isObject(object.measurements)
        ? (globalThis.Object.entries(object.measurements) as [string, any][]).reduce(
          (acc: { [key: number]: boolean }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Boolean(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: JobResult): unknown {
    const obj: any = {};
    if (message.jobId !== "") {
      obj.jobId = message.jobId;
    }
    if (message.shotNumber !== 0) {
      obj.shotNumber = Math.round(message.shotNumber);
    }
    if (message.state !== undefined) {
      obj.state = StateResponse.toJSON(message.state);
    }
    if (message.measurements) {
      const entries = globalThis.Object.entries(message.measurements) as [string, boolean][];
      if (entries.length > 0) {
        obj.measurements = {};
        entries.forEach(([k, v]) => {
          obj.measurements[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobResult>, I>>(base?: I): JobResult {
    return JobResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobResult>, I>>(object: I): JobResult {
    const message = createBaseJobResult();
    message.jobId = object.jobId ?? "";
    message.shotNumber = object.shotNumber ?? 0;
    message.state = (object.state !== undefined && object.state !== null)
      ? StateResponse.fromPartial(object.state)
      : undefined;
    message.measurements = (globalThis.Object.entries(object.measurements ?? {}) as [string, boolean][]).reduce(
      (acc: { [key: number]: boolean }, [key, value]: [string, boolean]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Boolean(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseJobResult_MeasurementsEntry(): JobResult_MeasurementsEntry {
  return { key: 0, value: false };
}

export const JobResult_MeasurementsEntry: MessageFns<JobResult_MeasurementsEntry> = {
  encode(message: JobResult_MeasurementsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== false) {
      writer.uint32(16).bool(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobResult_MeasurementsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobResult_MeasurementsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobResult_MeasurementsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Boolean(object.value) : false,
    };
  },

  toJSON(message: JobResult_MeasurementsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== false) {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobResult_MeasurementsEntry>, I>>(base?: I): JobResult_MeasurementsEntry {
    return JobResult_MeasurementsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobResult_MeasurementsEntry>, I>>(object: I): JobResult_MeasurementsEntry {
    const message = createBaseJobResult_MeasurementsEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? false;
    return message;
  },
};

function createBaseListJobsRequest(): ListJobsRequest {
  return { userId: "", stateFilter: 0, limit: 0, offset: 0 };
}

export const ListJobsRequest: MessageFns<ListJobsRequest> = {
  encode(message: ListJobsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.stateFilter !== 0) {
      writer.uint32(16).int32(message.stateFilter);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(32).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListJobsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListJobsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.stateFilter = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListJobsRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      stateFilter: isSet(object.stateFilter)
        ? jobStateFromJSON(object.stateFilter)
        : isSet(object.state_filter)
        ? jobStateFromJSON(object.state_filter)
        : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: ListJobsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.stateFilter !== 0) {
      obj.stateFilter = jobStateToJSON(message.stateFilter);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListJobsRequest>, I>>(base?: I): ListJobsRequest {
    return ListJobsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListJobsRequest>, I>>(object: I): ListJobsRequest {
    const message = createBaseListJobsRequest();
    message.userId = object.userId ?? "";
    message.stateFilter = object.stateFilter ?? 0;
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseJobList(): JobList {
  return { jobs: [], totalCount: 0 };
}

export const JobList: MessageFns<JobList> = {
  encode(message: JobList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.jobs) {
      JobStatus.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalCount !== 0) {
      writer.uint32(16).int32(message.totalCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JobList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseJobList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.jobs.push(JobStatus.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): JobList {
    return {
      jobs: globalThis.Array.isArray(object?.jobs) ? object.jobs.map((e: any) => JobStatus.fromJSON(e)) : [],
      totalCount: isSet(object.totalCount)
        ? globalThis.Number(object.totalCount)
        : isSet(object.total_count)
        ? globalThis.Number(object.total_count)
        : 0,
    };
  },

  toJSON(message: JobList): unknown {
    const obj: any = {};
    if (message.jobs?.length) {
      obj.jobs = message.jobs.map((e) => JobStatus.toJSON(e));
    }
    if (message.totalCount !== 0) {
      obj.totalCount = Math.round(message.totalCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JobList>, I>>(base?: I): JobList {
    return JobList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JobList>, I>>(object: I): JobList {
    const message = createBaseJobList();
    message.jobs = object.jobs?.map((e) => JobStatus.fromPartial(e)) || [];
    message.totalCount = object.totalCount ?? 0;
    return message;
  },
};

function createBaseClusterMetricsResponse(): ClusterMetricsResponse {
  return { activeWorkers: 0, queueDepth: 0, memoryUsagePercent: 0, jobsByState: {} };
}

export const ClusterMetricsResponse: MessageFns<ClusterMetricsResponse> = {
  encode(message: ClusterMetricsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.activeWorkers !== 0) {
      writer.uint32(8).int32(message.activeWorkers);
    }
    if (message.queueDepth !== 0) {
      writer.uint32(16).int32(message.queueDepth);
    }
    if (message.memoryUsagePercent !== 0) {
      writer.uint32(25).double(message.memoryUsagePercent);
    }
    globalThis.Object.entries(message.jobsByState).forEach(([key, value]: [string, number]) => {
      ClusterMetricsResponse_JobsByStateEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClusterMetricsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClusterMetricsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.activeWorkers = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.queueDepth = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 25) {
            break;
          }

          message.memoryUsagePercent = reader.double();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ClusterMetricsResponse_JobsByStateEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.jobsByState[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClusterMetricsResponse {
    return {
      activeWorkers: isSet(object.activeWorkers)
        ? globalThis.Number(object.activeWorkers)
        : isSet(object.active_workers)
        ? globalThis.Number(object.active_workers)
        : 0,
      queueDepth: isSet(object.queueDepth)
        ? globalThis.Number(object.queueDepth)
        : isSet(object.queue_depth)
        ? globalThis.Number(object.queue_depth)
        : 0,
      memoryUsagePercent: isSet(object.memoryUsagePercent)
        ? globalThis.Number(object.memoryUsagePercent)
        : isSet(object.memory_usage_percent)
        ? globalThis.Number(object.memory_usage_percent)
        : 0,
      jobsByState: isObject(object.jobsByState)
        ? (globalThis.Object.entries(object.jobsByState) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.jobs_by_state)
        ? (globalThis.Object.entries(object.jobs_by_state) as [string, any][]).reduce(
          (acc: { [key: number]: number }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ClusterMetricsResponse): unknown {
    const obj: any = {};
    if (message.activeWorkers !== 0) {
      obj.activeWorkers = Math.round(message.activeWorkers);
    }
    if (message.queueDepth !== 0) {
      obj.queueDepth = Math.round(message.queueDepth);
    }
    if (message.memoryUsagePercent !== 0) {
      obj.memoryUsagePercent = message.memoryUsagePercent;
    }
    if (message.jobsByState) {
      const entries = globalThis.Object.entries(message.jobsByState) as [string, number][];
      if (entries.length > 0) {
        obj.jobsByState = {};
        entries.forEach(([k, v]) => {
          obj.jobsByState[k] = Math.round(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClusterMetricsResponse>, I>>(base?: I): ClusterMetricsResponse {
    return ClusterMetricsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClusterMetricsResponse>, I>>(object: I): ClusterMetricsResponse {
    const message = createBaseClusterMetricsResponse();
    message.activeWorkers = object.activeWorkers ?? 0;
    message.queueDepth = object.queueDepth ?? 0;
    message.memoryUsagePercent = object.memoryUsagePercent ?? 0;
    message.jobsByState = (globalThis.Object.entries(object.jobsByState ?? {}) as [string, number][]).reduce(
      (acc: { [key: number]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseClusterMetricsResponse_JobsByStateEntry(): ClusterMetricsResponse_JobsByStateEntry {
  return { key: 0, value: 0 };
}

export const ClusterMetricsResponse_JobsByStateEntry: MessageFns<ClusterMetricsResponse_JobsByStateEntry> = {
  encode(message: ClusterMetricsResponse_JobsByStateEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClusterMetricsResponse_JobsByStateEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClusterMetricsResponse_JobsByStateEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClusterMetricsResponse_JobsByStateEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: ClusterMetricsResponse_JobsByStateEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClusterMetricsResponse_JobsByStateEntry>, I>>(
    base?: I,
  ): ClusterMetricsResponse_JobsByStateEntry {
    return ClusterMetricsResponse_JobsByStateEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClusterMetricsResponse_JobsByStateEntry>, I>>(
    object: I,
  ): ClusterMetricsResponse_JobsByStateEntry {
    const message = createBaseClusterMetricsResponse_JobsByStateEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

export type QuantumSchedulerService = typeof QuantumSchedulerService;
export const QuantumSchedulerService = {
  /** Submit a circuit job to the queue */
  submitJob: {
    path: "/qubit_engine.QuantumScheduler/SubmitJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobRequest): Buffer => Buffer.from(JobRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobRequest => JobRequest.decode(value),
    responseSerialize: (value: JobHandle): Buffer => Buffer.from(JobHandle.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobHandle => JobHandle.decode(value),
  },
  /** Get the status of a job */
  getJobStatus: {
    path: "/qubit_engine.QuantumScheduler/GetJobStatus" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobHandle): Buffer => Buffer.from(JobHandle.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobHandle => JobHandle.decode(value),
    responseSerialize: (value: JobStatus): Buffer => Buffer.from(JobStatus.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobStatus => JobStatus.decode(value),
  },
  /** Cancel a pending or running job */
  cancelJob: {
    path: "/qubit_engine.QuantumScheduler/CancelJob" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: JobHandle): Buffer => Buffer.from(JobHandle.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobHandle => JobHandle.decode(value),
    responseSerialize: (value: CancelResponse): Buffer => Buffer.from(CancelResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CancelResponse => CancelResponse.decode(value),
  },
  /** Stream results as they become available */
  streamJobResults: {
    path: "/qubit_engine.QuantumScheduler/StreamJobResults" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: JobHandle): Buffer => Buffer.from(JobHandle.encode(value).finish()),
    requestDeserialize: (value: Buffer): JobHandle => JobHandle.decode(value),
    responseSerialize: (value: JobResult): Buffer => Buffer.from(JobResult.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobResult => JobResult.decode(value),
  },
  /** List all jobs for a user */
  listJobs: {
    path: "/qubit_engine.QuantumScheduler/ListJobs" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListJobsRequest): Buffer => Buffer.from(ListJobsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListJobsRequest => ListJobsRequest.decode(value),
    responseSerialize: (value: JobList): Buffer => Buffer.from(JobList.encode(value).finish()),
    responseDeserialize: (value: Buffer): JobList => JobList.decode(value),
  },
  /** Get real-time cluster metrics for visualization */
  getClusterMetrics: {
    path: "/qubit_engine.QuantumScheduler/GetClusterMetrics" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: ClusterMetricsResponse): Buffer =>
      Buffer.from(ClusterMetricsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ClusterMetricsResponse => ClusterMetricsResponse.decode(value),
  },
} as const;

export interface QuantumSchedulerServer extends UntypedServiceImplementation {
  /** Submit a circuit job to the queue */
  submitJob: handleUnaryCall<JobRequest, JobHandle>;
  /** Get the status of a job */
  getJobStatus: handleUnaryCall<JobHandle, JobStatus>;
  /** Cancel a pending or running job */
  cancelJob: handleUnaryCall<JobHandle, CancelResponse>;
  /** Stream results as they become available */
  streamJobResults: handleServerStreamingCall<JobHandle, JobResult>;
  /** List all jobs for a user */
  listJobs: handleUnaryCall<ListJobsRequest, JobList>;
  /** Get real-time cluster metrics for visualization */
  getClusterMetrics: handleUnaryCall<Empty, ClusterMetricsResponse>;
}

export interface QuantumSchedulerClient extends Client {
  /** Submit a circuit job to the queue */
  submitJob(request: JobRequest, callback: (error: ServiceError | null, response: JobHandle) => void): ClientUnaryCall;
  submitJob(
    request: JobRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobHandle) => void,
  ): ClientUnaryCall;
  submitJob(
    request: JobRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobHandle) => void,
  ): ClientUnaryCall;
  /** Get the status of a job */
  getJobStatus(
    request: JobHandle,
    callback: (error: ServiceError | null, response: JobStatus) => void,
  ): ClientUnaryCall;
  getJobStatus(
    request: JobHandle,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobStatus) => void,
  ): ClientUnaryCall;
  getJobStatus(
    request: JobHandle,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobStatus) => void,
  ): ClientUnaryCall;
  /** Cancel a pending or running job */
  cancelJob(
    request: JobHandle,
    callback: (error: ServiceError | null, response: CancelResponse) => void,
  ): ClientUnaryCall;
  cancelJob(
    request: JobHandle,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CancelResponse) => void,
  ): ClientUnaryCall;
  cancelJob(
    request: JobHandle,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CancelResponse) => void,
  ): ClientUnaryCall;
  /** Stream results as they become available */
  streamJobResults(request: JobHandle, options?: Partial<CallOptions>): ClientReadableStream<JobResult>;
  streamJobResults(
    request: JobHandle,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<JobResult>;
  /** List all jobs for a user */
  listJobs(
    request: ListJobsRequest,
    callback: (error: ServiceError | null, response: JobList) => void,
  ): ClientUnaryCall;
  listJobs(
    request: ListJobsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: JobList) => void,
  ): ClientUnaryCall;
  listJobs(
    request: ListJobsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: JobList) => void,
  ): ClientUnaryCall;
  /** Get real-time cluster metrics for visualization */
  getClusterMetrics(
    request: Empty,
    callback: (error: ServiceError | null, response: ClusterMetricsResponse) => void,
  ): ClientUnaryCall;
  getClusterMetrics(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ClusterMetricsResponse) => void,
  ): ClientUnaryCall;
  getClusterMetrics(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ClusterMetricsResponse) => void,
  ): ClientUnaryCall;
}

export const QuantumSchedulerClient = makeGenericClientConstructor(
  QuantumSchedulerService,
  "qubit_engine.QuantumScheduler",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): QuantumSchedulerClient;
  service: typeof QuantumSchedulerService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
