apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - data-layer.yaml
  - core-services.yaml
  - application-modules.yaml
  - envoy-config.yaml
  - gateway-frontend.yaml
