global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'qubit_engine'
    static_configs:
      - targets: ['engine:9090']

  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:2112']
