#include "QuantumRegister.hpp"
#include "quantum.grpc.pb.h" // Generated by protoc
#include <grpcpp/grpcpp.h>

using grpc::ServerContext;
using grpc::Status;
using qubit_engine::QuantumCompute;
using qubit_engine::CircuitRequest;
using qubit_engine::StateResponse;
using qubit_engine::GateOperation;

class QubitEngineServiceImpl final : public QuantumCompute::Service {
    
    Status RunCircuit(ServerContext* context, const CircuitRequest* request,
                      StateResponse* response) override {
        
        // 1. Validation
        int n = request->num_qubits();
        if (n <= 0 || n > 25) {
            return Status(grpc::StatusCode::INVALID_ARGUMENT, "Qubits must be between 1 and 25");
        }

        // 2. Initialize Engine
        QuantumRegister qreg(n);

        // 3. Process Gates
        for (const auto& op : request->operations()) {
            switch (op.type()) {
                case GateOperation::HADAMARD:
                    qreg.applyHadamard(op.target_qubit());
                    break;
                case GateOperation::PAULI_X:
                    qreg.applyX(op.target_qubit());
                    break;
                case GateOperation::CNOT:
                    qreg.applyCNOT(op.control_qubit(), op.target_qubit());
                    break;
                default:
                    // Log unknown gate but continue
                    std::cerr << "Warning: Unknown gate type received." << std::endl;
            }
        }

        // 4. Serialize Response
        const auto& state = qreg.getStateVector();
        for (const auto& amp : state) {
            auto* c = response->add_state_vector();
            c->set_real(amp.real());
            c->set_imag(amp.imag());
        }

        return Status::OK;
    }
};
