apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qubit-engine.fullname" . }}-frontend
  labels:
    {{- include "qubit-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "qubit-engine.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "qubit-engine.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # No secrets needed here, mostly public static assets.
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: ENGINE_ADDR
              value: "{{ include "qubit-engine.fullname" . }}-backend-headless:50051"
            - name: SCHEDULER_ADDR
              value: "{{ include "qubit-engine.fullname" . }}-scheduler:50053"
            - name: REGISTRY_ADDR
              value: "{{ include "qubit-engine.fullname" . }}-registry:50052"
            - name: QUBIT_ENGINE_AUTH_TOKEN
              value: "default-secret-token" # In prod this would be a secretRef
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
            # Reusing default resources for simplicity, would tune in prod
